# Literature Review

### 2.1 Overview

This chapter describes previous studies that evaluate the effectiveness of IMT programs in several contexts. The chapter then describes previous attempts to simulation non-recurring congestion in transportation demand models. The chapter ends by identifying a potential avenue to combine these two methods into a single research effort.

### 2.2 IMT Effectiveness

Many states throughout the U.S. have established traffic incident management or TIM programs. At least 40 states and Washington DC have recognized the benefits of having dedicated traffic incident management programs and now have at least one freeway service patrol or similar program [@baird]. The various programs approach details of incident management differently; however, the goal of clearing roadways to reduce traffic delays remains the same. Traffic delays due to incidents result in lost time, consumption of extra fuel, and safety hazards for first responders (FHWA, 2020):

-   Every minute of incident delay multiplies traffic queues by a factor of four and increases the risk for secondary crashes.

-   The likelihood of a secondary crash increases by 2.8% for each minute the primary incident continues to be a hazard.

-   Faster response time has a well-documented relationship to the increased likelihood of crash survival.

-   Responder lives remain at risk every minute they are on the incident scene.

The Federal Highway Administration (FHWA) publishes the *Traffic Incident Management*

*Handbook* (FHWA, 2000) which defines traffic incident management as:

> *The systematic, planned, and coordinated use of human, institutional, mechanical, and technical resources to reduce the duration and impact of incidents and improve the safety of motorists, crash victims, and incident responders. (p. 1-1)*

The handbook details the process of how to implement a traffic incident management program as well as improve it. The manual addresses multiple facets of incident management including the role played by emergency medical teams, law enforcement, and other responders. For the purposes of this research, we focus on the dedicated traffic incident management teams operated by departments of transportation or similar agencies, and not other types of first responders.

The FHWA has established performance measures to develop a framework in which improvements to IMT operations and traffic can be quantified (FHWA, 2000). These measures are as follows:

-   Roadway clearance time (RCT) is the time between the first recordable awareness of the incident to time all lanes open for traffic flow.
-   Incident clearance time (ICT) is the time between the first recordable awareness of the incident and when the last responder has left the scene.
-   Secondary Crash occurs at the scene of an original crash or in the queue, including in the opposite direction.
-   Responder Struck By records any instance that a responder is struck by a vehicle while working the scene of an incident.

Using these or other similar performance measures, numerous studies have shown TIM programs have significant positive impact on traffic conditions. In recent research, [@schultz2019] found the implementation of IMTs to be significant. The research used a link between databases operated by UDOT and the Utah Highway Patrol to estimate the traffic reduction associated with IMT units responding to a crash site. The research concluded that deployment of IMT units decreases the excess travel time, excess user costs associated with congestion, and affects the volume of traffic in an incident.

@kim2012 , in a study of Maryland's Coordinated Highways Action Response Team (CHART) operations, developed a model using data provided by CHART to calculate costs associated with traffic delay. The researchers calculated a marginal cost to benefit ratio to determine optimal fleet size. To do this, the authors first calculated the estimated reduction in traffic delay under different highway response unit strategies. Then, fuel consumption and emissions, along with delay costs, were estimated given the time of delay and converted to monetary values. These values were then multiplied by the amount of time to find the marginal costs of traffic delay. The researchers found that the cost/benefit ratio decreases as the number of highway response units increases up until 7 units are deployed. This conclusion suggests that given the optimal number of response teams, the cost to benefit ratio is significant, however the benefit decreases as more teams are added. Finding optimal number of teams depends on factors like budget and network size along with incident occurrence.

@skabardonis1998 conclude in a study of the California Freeway Service Patrol (FSP) IMT service that, on average, total incident response time was 15 minutes longer when California Highway Patrol (CHP) unites responded without the support of FSP units. Using a system to assign a cost per traveler per unit of time to vehicles in the observed area, the authors determined FSP units had a cost to benefit ratio of 5:1. They also concluded that less time was spent on incidents (which includes vehicle breakdowns) by CHP officers.

@moore2004 further studied the effect of the California FSP units on secondary crashes -- when traffic caused by a previous crash is a factor in a subsequent crash -- in the L.A. metropolitan area. The research used data provided by the California Highway Patrol (CHP) First Incident Response Services Tracking system to identify secondary crashes. From the paper:

> *While avoiding secondary accidents proves only a small incentive to deploy FSP, the expected benefits of reducing already low secondary accident rates may be sufficient to justify accounting for these costs. (p. 285).*

#### 2.2.1 IMT Optimization

Given the evidence that IMTs improve traffic conditions in aspects such as traffic flow and monetary costs borne by governments and individuals, it follows that research would be done on maximizing the benefits of these teams. One method to maximize the benefit is to place the IMT units in the most advantageous location, optimizing their spatial effectiveness.

One of the major avenues researched to improve IMT programs is the allocation of individual trucks and the location of IMT depots where inactive trucks wait to be dispatched. Or alternatively, for systems where the IMT vehicles patrol, the research concerns the design of a service area or \"beat.\" The existing body of research approaches the problem of allocation in different methods. There exist multiple papers in which the problem is modeled statistically. Multiple variables are implemented into the statistical model, and specific performance measures are maximized given the constraints. Other research approaches the issue in a digital model.

@lou2011 researched methods to decrease IMT response time. A mixed-integer nonlinear optimization model was developed, and different algorithms were suggested to solve the problem. The research models the IMT units as roaming units within specific sections of a freeway and finds the optimal location of units to decrease response time. Incident frequency was determined by random generation on the network given mean and standard deviations of incident occurrence on each link in the network. The research focused on creating the algorithms and optimizing them for general implementation, and not on any specific network or with a goal to reduce response times in any one area. A numerical example was provided, by implementing a template \"Sioux Falls\" network into the model. Compared to the deployment plan used in Sioux Falls, the algorithm generated plans that could reduce total response time by 16.5-20.8%.

@ozbay2013 developed a model that provides information on resource allocation between \"depots\" or the staging areas of IMT units. A mixed-integer programming model with probabilistic constraints was developed in this research to approach the problem of IMT allocation within the various depots. Given that the probabilities of incident types on a network are known, IMT units are allocated to the incident scene, considering the future probabilities of incidents on the network. The objective of the model is to minimize incident management cost while maximizing utility. The function is applied to a simplified model of the South Jersey Highway network to demonstrate implementation of the model in decision making for IMT. Distribution of demand is based on traffic incident data from South New Jersey. In the results of the test, a number of depots and number of trucks assigned to each depot was found given a budget of \$500,000 for the whole program. No comparison to existing depot and unit distribution was made and therefore improvement because of the model was not quantified.

Digital models of IMT have been developed in the past with a variety of software packages. @pal2002 developed a digital model to replicate IMT impacts on traffic conditions. Overall traffic time in the system was used as the performance indicator of the units. The software program used was developed from scratch as existing programs at the time used in mesoscopic traffic simulation were incapable of simulating incident response units. Given probability distributions of crash data, vehicle speed and carrying capacity different configurations of response vehicles were simulated. Given the study results, suggestions were made regarding fleet size, hours of operation, patrol area design, and improvements regarding the dispatching policy.

These models, whether simulations or optimization problems, have been effective for what they were, but they fail to replicate real world scenarios in the way that a MATSim simulation can. Simulations like MATSim provide opportunity not only to incorporate real world data, but also to create more realistic networks and model drivers with tools like within day replanning, which will be discussed in later chapters.

An important consideration in determining the optimal location for the IMT units to be stationed is the metric by which the IMT is judged. The FHWA has established performance measures by which IMT teams were evaluated; however, some researchers have felt that other metrics proved helpful in specific scenarios. @pal2002 use a metric of total traffic time to analyze the model. Total traffic time is an effective approach as traffic slowdowns incur financial costs and other burdens on the individual and community [@bivina2016]. A financial cost-based model is implemented in some research of incident management programs. @kim2012 use assumed values of fuel price and pollution externalities gathered from previous research to assign a monetary value to consequences of traffic delay in time and environmental costs. The study focuses on optimizing IMT programs in general based on specific budgets. Kim and Chang do not implement IMT units directly in their traffic simulation. The total traffic time and financial costs are similar in their fundamental nature, in that financial costs are a function of the traffic delay. From another perspective, @ozbay2013 developed a statistical model where the costs associated with response times are minimized to meet budget constraints. Deciding what factors are most important to measure in the traffic simulation, like costs or response time, will help in the decision-making process behind IMT allocation.

### 2.3 Incident Modeling

Previous attempts to understand optimal IMT deployment have been primarily based on ad- hoc models, specially constructed utility functions, or similar stand-alone efforts, as outlined in the previous section. Rarely has there been an explicit attempt to model traffic delay associated with incident management, at least partially because research modeling the effects of incidents on region-scale traffic networks is a recent innovation.

#### 2.3.1 Dynamic Traffic Assignment

Traffic models are based on static assignment, dynamic assignment, or sometimes a combination of both. Static traffic assignment (STA) and dynamic traffic assignment (DTA) make the same behavioral assumption: drivers want to reach their destination in the shortest time possible. A static model achieves optimization by calculating route travel times, finding the shortest path, and adjusting routes toward equilibrium. The issue with static models is that they assume that all vehicles experience the same delay -- in particular, traffic flow is anisotropic and obeys causality **(Boyles, 2018).**

Dynamic modeling also aims to achieve equilibrium through route choice. Dynamic modeling shows how congestion varies over time, and it bases equilibration on experienced travel times, not instantaneous travel times. According to **Boyles (2018)**, "DTA is best applied when the input data are known with high certainty, only a few scenarios are needed, and detailed congestion and queueing information are critical" **(Boyles, 2018, p. 28)**. A study on the effects of congestion conducted by @sisiopiku2007 highlighted the applications of simulation-based DTA modeling on incident management. Her study argues that dynamic assignment is preferred over static when considering incident modeling. Sisiopiku describes her methodology as follows:

> *The overall approach in this study is to use the DTA capabilities to support decision-making for incident management. Unlike static assignment methods, which are based on average daily traffic and fail to capture the dynamic process of an incident, DTA is particularly appropriate for studying short-term planning applications such as evaluating various incident management options (p. 111).*

In this study, Sisiopiku used a simulation-based DTA model to assess the impacts of designed incident scenarios. She evaluated the effectiveness of candidate incident management plans and the impacts of traffic operations and control strategies for the analysis period.

Sisiopiku ran a base scenario under nonincidental conditions to provide a baseline for comparison. The second scenario simulated incident occurrence, but no incident information was available to the drivers, altering the incidents' duration and severity between iterations of the second scenario. Sisiopiku\'s third scenario was identical to the second, except information provisions were assumed to be available to the drivers. In the third scenario, the drivers took action to optimize their travel through the incident zone; information on predesignated diversion routes was provided to drivers through variable message signs (VMS) located upstream of the decision points [@sisiopiku2007].

The scenarios Sisopiku ran in Birmingham and Chicago revealed that travel time savings and traffic delay reduction could be achieved if information was provided to the agents following an incident. The study also shows how a simulation-based DTA model can simulate the impact of incidents on congestion and the impacts of different traffic operation and control strategies. The DTA tool used by Sisiopiku is known as Visual Interactive System for Transport Algorithms or VISTA, a tool commonly used in traffic modeling.

In a traffic incident simulation study, @wirtz2005 also conducted research and analysis on VISTA. In his study, Wirtz discusses the limitations of VISTA and DTA systems broadly. As part of adjusting routes toward equilibrium, dynamic systems assume that all motorists have perfect travel time information to be routed to the user-optimal path. For example, @sisiopiku2007 assumed a 100% compliance rate for the diversion routes provided to agents in her model. The assumption that drivers have perfect travel time information depends, in part, on how information reaches them; radio traffic reports, the internet, or VMS are some communication methods. @wirtz2005 found that \"less-informed drivers spend more time traveling than necessary, representing a departure from the user-optimal traffic conditions simulated by VISTA\" [@wirtz2005]. The advancements in and increased accessibility of personal global positioning system (GPS) information have made it more likely for a user to find an optimal path following a traffic incident. The assumptions built into a model are crucial in its functionality; other key factors include the model's scope and scale.

#### 2.3.2 Types of Models

DTA models generally fall into two camps: microscopic and mesoscopic. Microscopic models run on small scales and track the trajectories of individuals. In contrast, mesoscopic models are more aggregated and simplify variations in behavior; they involve elements of both static modeling and dynamic microscopic models **(Boyles, 2018)**. The level of detail in microscopic models makes them highly realistic but impractical for modeling large regions. A mesoscopic model that shows the paths of individual vehicles but ignores traffic flow issues like turn conflicts and lane changes would work well for modeling traffic flow over a greater area **(Boyles, 2018)**.

VISTA is an example of a mesoscopic model which showcases DTA's capability for incident modeling. Microscopic models, like VISSIM, can also be used for incident modeling. Microscopic models can track precise locations of vehicles, driver behavior, and even vehicle characteristics; this makes the models extremely realistic but impractical for modeling large regions **(Boyles, 2018)**. In Australia, @dia2006 used VISSIM to evaluate incident management impacts on two arterial routes (Coronation Drive and Milton Road) connecting the western suburbs of Brisbane and the Central Business District. Another framework used for incident modeling is the traffic simulator JDSMART. This model was used by @vanlint2012 for incident simulation and to study how roadway policies influence congestion.

#### 2.3.3 MATSim

One software recently used for incident modeling and can produce microscopic and mesoscopic models is the Multi-Agent Transport Simulation Toolkit (MATSim). MATSim is an open-source framework for implementing large-scale agent-based transport simulations that assigns traffic between origins and destinations using a mesoscopic queue-based approach. Agents representing individuals attempt to find the shortest paths between their activities.

**Dobler (2016)** wrote a chapter in the MATSim manual on the necessity of a within-day replanning tool and its usage in MATSim. He explains that an iterative approach to MATSim modeling works well for ideal circumstances and achieving user equilibrium. Still, this approach will produce illogical behavior when accounting for unexpected events, such as altering route assignments before the time in which an incident occurs. Figure 1: Within-day replanning approach for a MATSim routing problem. shows an agent (a simulated person) traveling from the red dot to the green dot. Along this agent's assigned route, a crash occurred at 14:02. Due to the iterative approach, the agent chooses a different route at 14:00, two minutes before the crash. This illogical behavior shows how an iterative approach is not ideal for modeling unexpected behavior. A within-day replanning method only runs a single iteration, not multiple.
