project:
  type: book

# This defines the .qmd files that are in your document
book:
  title: "Simulating Incident Management Team Response and Performance"
  author:
    # - name: Gregory S. Macfarlane
    #   orcid: 0000-0003-3999-7584
    #   email: gregmacfarlane@gmail.com
    #   affiliations:
    #     - name: Civil and Construction Engineering Department, Brigham Young University
    #       address: 430 EB
    #       city: Provo
    #       state: UT
    #       postal-code: 84602
    - name: Daniel Jarvis
      email: 
      affiliations:
        - name: Brigham Young University
          address: 430 EB
          city: Provo
          state: UT
          postal-code: 84602
    # - name: Brynn Woolley
    #   email: 
    #   affiliations:
    #     - name:  Brigham Young University
    #       address: 430 EB
    #       city: Provo
    #       state: UT
    #       postal-code: 84602
    # to add additional authors, simply add another -name: tag 
  date: "6/25/2023"
  chapters:
    - index.qmd
    - 02_literature.qmd
    - 03_methods.qmd
    - 04_results.qmd
    - 05_conclusion.qmd
    - references.qmd
  appendices: 
    - event_handlers.qmd
  abstract: |
    The effectiveness of Incident Management Teams (IMT) in reducing the duration 
    and impact of traffic incidents is well-documented. The capacity of large-scale 
    simulation models to illustrate the negative effects of these incidents on 
    vehicle delays and excess user costs (EUC) is also widely recognized. 
    However, there is a gap in research integrating large-scale simulation modeling 
    with IMT performance analysis. This study uses the Multi-Agent Transport Simulation 
    (MATSim) to assess how incidents and IMT influence Utah’s Wasatch Front regional 
    network and evaluates their performance under hypothetical scenarios.
    
    Our findings validate the role of IMT in decreasing delays and EUC. 
    The simulation investigates the potential effects of increased incident 
    frequency and IMT expansion, revealing that more incidents increase delays, 
    whereas more IMT units can mitigate these effects and improve response times.
    
    The MATSim model we developed demonstrates the potential of dynamic large-scale 
    modeling to evaluate incident management strategies in ways that previous 
    studies did not. This model could serve as a valuable tool for further evaluating 
    the performance of Utah’s IMT program, with the potential to offer new perspectives 
    on optimizing team deployment and scheduling efficiency.

bibliography: references.bib
csl: apa.csl
# Layout options are simple/fancy, oneside/twoside, and masters/phd.
# Leave options blank for defaults.
# Defaults are simple for document style, and masters for degree type.
layout: fancy, oneside, masters
# If your degree is not a PhD or MS, then you can overwrite the degree using 
# the \degree command: \degree{Bachelors of Science}
# degree: Bachelors of Science with University Honors
department: Civil and Construction Engineering
# list your chair and any other members of your committee
chair: Gregory S. Macfarlane
committee:
  - Grant G. Schultz
  - Gustavious P. Williams
# Include any keywords you would like for your thesis/dissertation
keywords:
  - Incident Management Teams
  - Incident Simulation
  - Transportation Modeling
acknowledgments: | 
  I want to extend my gratitude to the Utah Department of Transportation for 
  their substantial financial backing, which was essential for the completion 
  of my research and thesis project. I am equally grateful to the technical 
  advisory committee, whose expert guidance and invaluable feedback were 
  critical throughout my research endeavor. Their in-depth understanding of 
  Utah’s traffic incident management programs was a crucial contributor to the 
  successful outcome of this study.
  
  My sincere thanks are extended to my fellow research assistants at BYU—Joel Hyer, 
  Harrison Holdsworth, and Brynn Woolley. Joel’s insightful analysis and the vital 
  data he provided from the IMT Performance Phase III project were indispensable. 
  Harrison's wide-ranging input, from his diligent compilation of research on IMT 
  optimization to his collaborative efforts in drafting the literature review, 
  proved instrumental. His ability to seamlessly connect Joel's work with my 
  research was invaluable. Brynn's expertise in developing the transportation model, 
  her astute analysis of its findings, and her assistance in refining and 
  editing this report added significantly to the quality of my work.
  
  Profound appreciation is due to my faculty advisors and the members of my 
  thesis committee, Drs. Macfarlane, Schultz, and Williams, for their unwavering 
  support. I am particularly indebted to Dr. Macfarlane for his exceptional mentorship 
  as an advisor, educator, and friend. His patience, wisdom, and encouragement have 
  been instrumental at every stage of my academic journey. His faith in me and 
  consistent support have been the pillars of my personal development 
  and the achievements of this research.
  
  Lastly, I offer thanks to my parents, Duane and Jodi Jarvis, for their 
  steadfast encouragement and belief in me throughout my academic pursuits. 
  Their encouragement and reassurance have been a source of immense strength, 
  especially during this significant stage of my life. I am forever grateful 
  for the stability and unwavering support they have so selflessly provided.

format:
  html:
    theme: cosmo
  byu-thesis-pdf:
    keep-tex: true
    highlight-style: arrow
  # elsevier-pdf:
  #   include-in-header: 
  #     - packages.tex
  #   journal:
  #     name: Transportation Research Part A
  #     cite-style: authoryear
  #   keep-tex: true
  #   top-level-division: section
  #   toc: false


editor: visual