project:
  type: book

# This defines the .qmd files that are in your document
book:
  title: "Simulating Incident Management Team Response and Performance"
  author:
    # - name: Gregory S. Macfarlane
    #   orcid: 0000-0003-3999-7584
    #   email: gregmacfarlane@gmail.com
    #   affiliations:
    #     - name: Civil and Construction Engineering Department, Brigham Young University
    #       address: 430 EB
    #       city: Provo
    #       state: UT
    #       postal-code: 84602
    - name: Daniel Jarvis
      email: 
      affiliations:
        - name: Brigham Young University
          address: 430 EB
          city: Provo
          state: UT
          postal-code: 84602
    # - name: Brynn Woolley
    #   email: 
    #   affiliations:
    #     - name:  Brigham Young University
    #       address: 430 EB
    #       city: Provo
    #       state: UT
    #       postal-code: 84602
    # to add additional authors, simply add another -name: tag 
  date: "6/25/2023"
  chapters:
    - index.qmd
    - 02_literature.qmd
    - 03_methods.qmd
    - 04_results.qmd
    - 05_conclusion.qmd
    - references.qmd
  appendices: 
    - event_handlers.qmd
  abstract: |
    The effectiveness of the Incident Management Teams (IMT) is well documented, 
    and the capability of large-scale simulation models to demonstrate the impacts 
    of incidents is also widely acknowledged. However, using a large-scale 
    simulation approach to analyze IMT performance remains largely unresearched. 
    This study employs the Multi-Agent Transport Simulation (MATSim) to model the 
    effects of incidents and IMT responses on the regional network in Utah's Wasatch Front.
    
    This simulation approach largely confirmed findings from similar studies, 
    demonstrating that IMT effectively reduce incident delays and decrease congestion
    for users. Furthermore, the simulation allowed an exploration of the 
    hypothetical impacts of increasing the number of incidents in a scenario 
    or expanding the number of IMT within a system. 
    Variations in these parameters revealed that increased incidents strain the 
    system and cause additional delays. In contrast, additional IMT help to mitigate 
    the impact of those incidents and improved average IMT response times.

    While the MATSim model we built has room for improvement, it illustrates 
    how large-scale dynamic modeling can evaluate incident management strategies 
    beyond previous analysis methods. Looking ahead, the model developed in this 
    study shows promise as a tool for examining IMT performance in ways that previous 
    studies have not.

bibliography: references.bib
csl: apa.csl
# Layout options are simple/fancy, oneside/twoside, and masters/phd.
# Leave options blank for defaults.
# Defaults are simple for document style, and masters for degree type.
layout: fancy, oneside, masters
# If your degree is not a PhD or MS, then you can overwrite the degree using 
# the \degree command: \degree{Bachelors of Science}
# degree: Bachelors of Science with University Honors
department: Civil and Construction Engineering
# list your chair and any other members of your committee
chair: Gregory S. Macfarlane
committee:
  - Grant G. Schultz
  - Gustavious P. Williams
# Include any keywords you would like for your thesis/dissertation
keywords:
  - Demand Responsive Transport
  - Incident Management Teams
  - MATSim – Multi-Agent Transport Simulation
  - Network Change Events
  - Transportation Modeling
acknowledgments: | 
  I would like to express my sincere gratitude to the Utah Department of Transportation for their generous financial support, which was instrumental in bringing this research and thesis project to fruition. My heartfelt thanks also go to the technical advisory committee, whose guidance and constructive feedback have been invaluable throughout the course of this research. Their deep insights into Utah’s traffic incident management programs played a crucial role in shaping this work.
  
  I am also immensely grateful to my fellow research assistants at BYU, Joel Hyer, Harrison Holdsworth, and Brynn Woolley. Joel, through his work on the IMT Performance Phase III project, provided essential information on IMT performance, as well as incident data and metrics, all of which were pivotal to this project. Harrison’s contributions were multifaceted; he not only compiled research on IMT optimization, but also assisted in writing the literature review for this report and served as a vital link between Joel’s project and my own research. Brynn’s expertise was invaluable in the development of the transportation model used in this project, and her assistance in analyzing its outputs, as well as her help in the production and editing of this thesis document, were greatly appreciated.
  
  I want to express my profound appreciation to my faculty advisors and the members of the thesis committee, Drs. Macfarlane, Schultz, and Williams. Special gratitude is extended to Dr. Macfarlane, whose role as an outstanding faculty advisor, teacher, mentor, and friend has been invaluable throughout my academic journey. His patience, counsel, and support have been crucial at every phase of this project. I am deeply thankful for his belief in my potential and his consistent encouragement, which have been instrumental in my personal growth and the success of this research.

format:
  html:
    theme: cosmo
  byu-thesis-pdf:
    keep-tex: true
    highlight-style: arrow
  # elsevier-pdf:
  #   include-in-header: 
  #     - packages.tex
  #   journal:
  #     name: Transportation Research Part A
  #     cite-style: authoryear
  #   keep-tex: true
  #   top-level-division: section
  #   toc: false


editor: visual