# Introduction

[^1] Incident Management Teams (IMT) are service vehicles that collaborate with highway patrol units to manage traffic after an incident and provide timely roadside assistance. They are strategically important for improving highway operations, particularly during peak traffic times, helping to effectively alleviate congestion and associated user costs. Capable of quickly addressing a range of incidents from minor vehicle breakdowns to severe multi-car collisions, IMT are crucial in controlling traffic and restoring normal flow on the roadways.

States like Utah have long benefited from IMT, witnessing notable reductions in congestion and traffic-related costs [@bennett2022]. The effectiveness of IMT, influenced by factors such as response times [@bennett2021], fleet size [@kim2012], and deployment locations [@ozbay2013], is well-documented. However, the current understanding primarily stems from ad-hoc models and independent initiatives, leaving a gap in regional-scale traffic delay modeling associated with incident management. 

A study conducted by @kaddoura2018 highlights the potential of large-scale traffic models to assess the regional impact of incidents, demonstrating that such incidents can significantly increase congestion and average vehicle travel times within a simulated network. However, their model does not evaluate the impact of IMT strategies. This research aims to address this limitation by merging insights on IMT effectiveness with a large-scale regional traffic model. This approach is designed to highlight the impacts of traffic incidents and IMT interventions within a simulated network.

In this research, we present a model of IMT response to incidents on freeways in the Wasatch Front region of Utah. The model uses the Multi Agent Transportation Simulation (MATSim) framework to evaluate IMT effectiveness within various traffic incident scenarios. After conducting 60 simulations, we compared their outcomes and evaluated the effectiveness of IMT at improving traffic conditions and reducing congestion.

The paper proceeds in a typical order. [The literature review](#sec-literature) contains a discussion of previous research into IMT effectiveness and optimization. The [methodology section](#sec-methods) describes the simulation and scenario construction, while [the results](#sec-results) present the findings of the analysis alongside a discussion of their implications. The paper's [conclusions](#sec-conclusions) provide an outline of future research motivated by this study's limitations.

[^1]: This is a draft of a manuscript, authored by Jarvis, Macfarlane, Woolley, and Schultz. It is prepared to be submitted to the Transportation Research Part C. Any use of the pronoun 'we' in this document refers collectively to the research team, all of whom will be listed as authors upon the manuscript's publication as an article.