\documentclass[fancy, oneside, mastersfancy, ms]{byuthesis}
\usepackage{bookmark}


\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newlength{\cslentryspacingunit} % times entry-spacing
\setlength{\cslentryspacingunit}{\parskip}
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
  \let\oldpar\par
  \def\par{\hangindent=\cslhangindent\oldpar}
  \fi
  % set entry spacing
  \setlength{\parskip}{#2\cslentryspacingunit}
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{siunitx}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage[utf8]{inputenc}
\usepackage{makecell}
\usepackage{xcolor}
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{bookmark}{}{\usepackage{bookmark}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[skins,breakable]{tcolorbox}}
\makeatother
\makeatletter
\@ifundefined{shadecolor}{\definecolor{shadecolor}{rgb}{.97, .97, .97}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\makeatother

\title{Simulating Incident Management Team Response and Performance}
\author{Daniel Jarvis}

% On the custom title page, use the same title, but format as you like
\customtitle{Simulating Incident Management Team Response and
Performance}

% This is the date of graduation
\date{2023-06-25}

% If your degree is not a PhD or MS, then you can overwrite the degree using 
% the \degree command: \degree{Bachelors of Basics}

% Your department
\department{Civil and Construction Engineering}

% The names of your committee members
\committeechair{Gregory S. Macfarlane}
  \committeemember{Grant G. Schultz}
  \committeemember{Gustavious P. Williams}

\keywords{
    Demand Responsive Transport; Incident Management Teams; MATSim --
Multi-Agent Transport Simulation; Network Change Events;  
    Transportation Modeling
}

\begin{document}

\frontmatter
\titlepage
\cleardoublepage

\customtitlepage
\cleardoublepage


  \begin{abstract}
The abstract is a crucial component of any scientific paper, as it
provides a summary of the research and its main findings. This paper
provides guidelines for writing an effective scientific abstract. The
first step is to identify the key elements of the research, such as the
research question, methods, results, and conclusions. Next, the abstract
should be written in a clear and concise manner, using simple language
and avoiding technical jargon. The abstract should also be structured,
with a clear introduction, methods section, results section, and
conclusion. Additionally, the abstract should accurately and succinctly
convey the main findings of the research, highlighting the significance
and implications of the work. By following these guidelines, researchers
can ensure that their abstract effectively communicates the key aspects
of their research and attracts the attention of potential readers. -
Written by ChatGPT
\end{abstract}
\cleardoublepage

\begin{acknowledgments}
I would like to express my sincere gratitude to the Utah Department of
Transportation for their generous financial support, which was
instrumental in bringing this research and thesis project to fruition.
My heartfelt thanks also go to the technical advisory committee, whose
guidance and constructive feedback have been invaluable throughout the
course of this research. Their deep insights into Utah's traffic
incident management programs played a crucial role in shaping this work.

I am also immensely grateful to my fellow research assistants at BYU,
Joel Hyer, Harrison Holdsworth, and Brynn Woolley. Joel, through his
work on the IMT Performance Phase III project, provided essential
information on IMT performance, as well as incident data and metrics,
all of which were pivotal to this project. Harrison's contributions were
multifaceted; he not only compiled research on IMT optimization, but
also assisted in writing the literature review for this report and
served as a vital link between Joel's project and my own research.
Brynn's expertise was invaluable in the development of the
transportation model used in this project, and her assistance in
analyzing its outputs, as well as her help in the production and editing
of this thesis document, were greatly appreciated.

I want to express my profound appreciation to my faculty advisors and
the members of the thesis committee, Drs. Macfarlane, Schultz, and
Williams. Special gratitude is extended to Dr.~Macfarlane, whose role as
an outstanding faculty advisor, teacher, mentor, and friend has been
invaluable throughout my academic journey. His patience, counsel, and
support have been crucial at every phase of this project. I am deeply
thankful for his belief in my potential and his consistent
encouragement, which have been instrumental in my personal growth and
the success of this research.
\end{acknowledgments}
\cleardoublepage

	\tableofcontents*
	\cleardoublepage

	\listoffigures
	\cleardoublepage

	\listoftables
	\cleardoublepage

\mainmatter
\bookmarksetup{startatroot}

\hypertarget{introduction}{%
\chapter{Introduction}\label{introduction}}

Incident Management Teams (IMT) are service vehicles that collaborate
with highway patrol teams to manage traffic after an incident and
provide timely roadside assistance. They are strategically important for
improving highway operations, particularly during peak traffic times,
helping to effectively alleviate congestion and associated user costs.
Capable of quickly addressing a range of incidents, from minor vehicle
breakdowns to severe multi-car collisions, IMT are crucial in
controlling traffic and restoring normal flow on the roadways.

States like Utah have long benefited from IMT, witnessing notable
reductions in congestion and traffic-related costs (Bennett, 2021). The
effectiveness of IMT, influenced by factors such as response times
(Schultz et al., 2019), fleet size (Kim et al., 2012), and deployment
locations (Ozbay et al., 2013), is well-documented. However, the current
understanding primarily stems from ad-hoc models and independent
initiatives, leaving a gap in regional-scale traffic delay modeling
associated with incident management.

A study conducted by Kaddoura \& Nagel (2018) highlights the potential
of large-scale traffic models to evaluate the regional impact of
incidents. However, their model does not evaluate the impact of IMT
strategies. This research aims to address this limitation, merging
insights on IMT effectiveness with a large-scale regional traffic model.
This approach is meant to highlight the impacts of traffic incidents and
IMT interventions on a simulated network.

In this research we utilized the the Mutli-Agent Transportion Simulation
(MATSim) to model roadway conditions along the Wasatch Front region of
Utah. The model was used to evaluate IMT effectiveness within various
traffic incident scenarios. After conducting 60 simulations, we compared
their outcomes and evaluated the effectiveness of IMT at improving
traffic conditions and reducing congestion.

This paper contributes to the existing body of knowledge on IMT
effectiveness and traffic incident modeling. It underscores the
importance of strategic IMT deployment and the necessity for continuous
evaluation and adaption of IMT strategies to meet the evolving demands
of highway operation systems. The paper proceeds in a typical order.
\protect\hyperlink{sec-literature}{Literature Review} contains a
discussion of previous research into IMT effectiveness and optimization.
\protect\hyperlink{sec-methods}{Methodology} describes the simulation
and scenario construction, while
\protect\hyperlink{sec-results}{Results} presents the findings of the
analysis alongside a discussion of their implications. The paper
concludes in \protect\hyperlink{sec-conclusions}{Conclusions} with an
outline of future research motivated by this study's limitations.

\bookmarksetup{startatroot}

\hypertarget{sec-literature}{%
\chapter{Literature Review}\label{sec-literature}}

Traffic incident management in general --- and IMT in particular --- are
not strictly new innovations. The Federal Highway Administration (FHWA)
publishes the \emph{Traffic Incident Management Handbook} (FHWA, 2000),
which defines traffic incident management as:

\begin{quote}
\emph{The systematic, planned, and coordinated use of human,
institutional, mechanical, and technical resources to reduce the
duration and impact of incidents and improve the safety of motorists,
crash victims, and incident responders. (p.~1-1)}
\end{quote}

The handbook details the process of how to implement a traffic incident
management program as well as improve it. The manual covers various
aspects of incident management, including the responsibilities of
emergency medical teams, law enforcement, and other responding entities.
For this research, we focus on the dedicated traffic incident management
teams operated by departments of transportation or similar agencies and
not other types of first responders.

The FHWA has established performance measures to develop a framework to
quantify improvements to IMT operations and traffic (FHWA, 2000). Two
specific measures related to this research are: first, roadway clearance
time (RCT) is the time between the first recordable awareness of the
incident to the time all lanes open for traffic flow; second, incident
clearance time (ICT) is the time between the first recordable awareness
of the incident and when the last responder has left the scene.

Numerous studies have assessed the impact of Traffic Incident Management
(TIM) programs on traffic conditions, utilizing performance indicators
such as those provided by the Federal Highway Administration (FHWA). A
particularly noteworthy study conducted by Schultz et al. (2019)
explores the relationship between the response times of Incident
Management Teams (IMT) and various traffic parameters, including roadway
clearance time (RCT), estimated travel time (ETT), and excess user cost
(EUC). This research leveraged interconnected data from the Utah
Department of Transportation (UDOT) and the Utah Highway Patrol, aiming
to quantify the traffic improvements resulting from swift IMT
interventions at accident sites. Analyzing 121 incidents, the study
found that a one-minute delay in IMT response correlated with a
0.8-minute increase in RCT. This delay also impacted an additional 93
vehicles, added roughly 34.6 minutes to the network's total estimated
travel time, and resulted in an extra \$925 in excess user costs. In
essence, Schultz et al. (2019) established a clear connection between
timely IMT responses and improved traffic conditions, underscoring the
importance of rapid intervention.

Kim et al. (2012), in a study of Maryland's Coordinated Highways Action
Response Team (CHART) operations, devised a model using CHART's data to
compute the costs associated with traffic delay. The team established a
marginal cost-to-benefit ratio to discern the ideal fleet size. They
first estimated the reduction in traffic delay under various highway
response unit strategies. Subsequently, they calculated the costs of
fuel consumption, emissions, and delay times and converted these into
monetary values. These figures were then multiplied by the delay's
duration to obtain the traffic delay's marginal costs. The research
determined that each additional unit added provided a greater benefit
than its associated cost until seven highway response units were
deployed. This finding implies that while there is a significant
cost-to-benefit ratio with the optimal number of response teams, the
benefit diminishes when adding too many teams. Determining the ideal
number of teams is a function of budget, network size, and incident
frequency.

Skabardonis et al. (1998) concluded in a study of the California Freeway
Service Patrol (FSP) IMT service that, on average, total incident
response time was 15 minutes longer when California Highway Patrol (CHP)
units responded without the support of IMT units. Using a system to
assign a cost per traveler per unit of time to vehicles in the observed
area, the authors determined that IMT units had a cost-to-benefit ratio
of 5:1. They also concluded that CHP officers spent less time on
incidents (including vehicle breakdowns) when assisted by incident
management team services.

\hypertarget{imt-optimization}{%
\section{IMT Optimization}\label{imt-optimization}}

Given the evidence that IMT programs improve traffic conditions and
reduce costs for government entities and individuals, it becomes
paramount to further research avenues to maximize these benefits. One
effective strategy is the strategic placement of IMT units, optimizing
their spatial effectiveness to enhance their impact.

Enhancing IMT programs often focus on the precise deployment of
individual trucks and the strategic positioning of IMT
depots---locations where inactive trucks await dispatch. For scenarios
where IMT vehicles are actively on patrol, research often concerns
designing an efficient service area or ``beat.'' Various methodologies
have been applied to tackle this allocation challenge. While some
studies employ statistical models, incorporating a range of variables to
maximize specific performance measures given constraints, others opt for
digital modeling as a solution.

For instance, Lou et al. (2011) explored strategies aimed at minimizing
IMT response time. They developed a mixed-integer nonlinear optimization
model and proposed different algorithms to address this problem. The
research modeled IMT units as roaming entities within specific freeway
sections, aiming to determine the optimal unit locations for minimizing
response times. Incident frequencies were generated randomly on the
network, given mean and standard deviations of incident occurrence on
each link in the network. The study focused on developing and optimizing
these algorithms for broad implementation rather than focusing on any
particular network or reducing response times in specific areas. They
implemented a template ``Sioux Falls'' network into the model as a
practical demonstration. Compared to the existing deployment plan in
Sioux Falls, the algorithm-generated plans could potentially reduce
total response time by 16.5-20.8\%.

Ozbay et al. (2013) designed a mixed-integer programming model with
probabilistic constraints to optimize the allocation of Incident
Management Team (IMT) units across ``depots'' or staging areas in New
Jersey. This innovative approach, grounded in known probabilities of
various incident types, strategically positions IMT units to respond to
incidents, taking into account future probabilities on the network. The
primary goals were to minimize incident management costs and maximize
utility. The model was applied to a simplified South Jersey Highway
network, utilizing traffic incident data from the region to inform
demand distribution. Through this application, an optimal number of
depots and truck assignments were determined based on a \$500,000 budget
for the entire program. However, the lack of a comparative analysis with
pre-existing depot and unit distributions meant that the exact
improvements yielded by the model remained unquantified.

Digital models of IMTs have been developed in the past with various
software packages. Pal \& Sinha (2002) developed a digital model to
replicate IMT impacts on traffic conditions. Overall traffic time in the
system was used as the performance indicator of the units. The software
program was developed from scratch as existing programs at the time used
in mesoscopic traffic simulation could not simulate incident response
units. Various configurations of response vehicles were simulated using
probability distributions of crash data, vehicle speed, and carrying
capacity. Given the study results, suggestions were made regarding fleet
size, hours of operation, patrol area design, and improvements regarding
the dispatching policy.

These models, whether simulations and optimization problems, have served
their intended purposes effectively, but they fall short in mimicking
real-world scenarios as accurately as MATSim simulations do. Unlike
other models, MATSim allows for the integration of real-world data,
facilitating the creation of more realistic network simulations.
Additionally, it provides tools such as network change events and
within-day replanning, which contribute to a more accurate modeling of
driver behavior. These tools and their applications will be explored in
more detail in subsequent chapters.

An important consideration in determining the optimal location and fleet
size of IMT units is the metric by which the system is judged. The FHWA
has established performance measures by which IMTs were evaluated;
however, some researchers have felt that other metrics proved helpful in
specific scenarios. Pal \& Sinha (2002) use a metric of total traffic
time to analyze the model. Total traffic time is a practical approach as
traffic slowdowns incur financial costs and other burdens on the
individual and community (Bivina et al., 2016-01-01, 2016-01). An
economic cost-based model is implemented in some research on incident
management programs. Kim et al. (2012) use assumed values of fuel price
and pollution externalities gathered from previous research to assign a
monetary value to consequences of traffic delay in time and
environmental costs. The study focuses on optimizing IMT programs in
general based on specific budgets. Kim and Chang do not implement IMT
units directly in their traffic simulation. The total traffic time and
financial costs are similar in their fundamental nature in that
financial costs are a function of the traffic delay. From another
perspective, Ozbay et al. (2013) developed a statistical model where the
costs associated with response times are minimized to meet budget
constraints. Deciding what factors are most important to measure in the
traffic simulation, like costs or response time, will help the
decision-making process behind IMT allocation.

\hypertarget{incident-modeling}{%
\section{Incident Modeling}\label{incident-modeling}}

As outlined in the preceding section, previous attempts to understand
optimal IMT deployment have been primarily based on ad-hoc models,
specially constructed utility functions, or similar stand-alone efforts.
Rarely has there been an explicit attempt to model traffic delay
associated with incident management, at least partially because research
modeling the effects of incidents on region-scale traffic networks is a
recent innovation.

Traffic models are based on static assignment, dynamic assignment, or
sometimes a combination of both. Static traffic assignment (STA) and
dynamic traffic assignment (DTA) make the same behavioral assumption:
drivers want to reach their destination in the shortest time possible. A
static model achieves optimization by calculating route travel times,
finding the shortest path, and adjusting routes toward equilibrium. The
issue with static models is that they assume that all vehicles
experience the same delay -- in particular, traffic flow is anisotropic
and obeys causality (Boyles, 2018).

Dynamic modeling also aims to achieve equilibrium through route choice.
Dynamic modeling shows how congestion varies over time, and it bases
equilibration on experienced travel times, not instantaneous travel
times. According to Boyles (2018), ``DTA is best applied when the input
data are known with high certainty, only a few scenarios are needed, and
detailed congestion and queueing information are critical'' (Boyles,
2018, p. 28). A study on the effects of congestion conducted by
Sisiopiku et al. (2007) highlighted the applications of simulation-based
DTA modeling on incident management. Her study argues that dynamic
assignment is preferred over static when considering incident modeling.
Sisiopiku describes her methodology as follows:

\begin{quote}
\emph{The overall approach in this study is to use the DTA capabilities
to support decision-making for incident management. Unlike static
assignment methods, which are based on average daily traffic and fail to
capture the dynamic process of an incident, DTA is particularly
appropriate for studying short-term planning applications such as
evaluating various incident management options (p.~111).}
\end{quote}

In this study, Sisiopiku used a simulation-based DTA model to assess the
impacts of designed incident scenarios. She evaluated the effectiveness
of candidate incident management plans and the impacts of traffic
operations and control strategies for the analysis period.

Sisiopiku initially conducted a base scenario under non-incidental
conditions, which served as a benchmark for comparison. The follow-up
scenario introduced an incident simulation, with the key caveat that
drivers were kept uninformed about the incident. The duration and
severity of the incidents were manipulated between different iterations
of this second scenario. The third scenario mirrored the second but
introduced information provision to the drivers. In this scenario,
drivers were empowered to optimize their route through the incident zone
and given access to information about pre-planned diversion paths. This
information was relayed to the drivers through Variable Message Signs
(VMS) strategically positioned upstream of decision points, as detailed
in Sisiopiku's 2007 study.

The scenarios Sisopiku ran in Birmingham and Chicago revealed that
travel time savings and traffic delay reduction could be achieved if
information was provided to the agents following an incident. The study
also shows how a simulation-based DTA model can simulate the impact of
incidents on congestion and the impacts of different traffic operation
and control strategies. The DTA tool Sisiopiku uses is Visual
Interactive System for Transport Algorithms or VISTA, a tool commonly
used in traffic modeling.

Echoing Sisiopiku's usage of VISTA, Wirtz et al. (2005) also undertook
an in-depth analysis of this tool in his 2005 traffic incident
simulation study. Wirtz elaborated on the limitations of both VISTA and
DTA systems. As part of their route adjustment towards equilibrium,
these systems presume all drivers possess flawless travel time
information for routing to the user-optimal path. For instance,
Sisiopiku, in her 2007 study, presumed a 100\% compliance rate for the
diversion routes provided to the drivers in her model. The validity of
this assumption of perfect travel time information is partially
contingent on the communication medium---radio traffic reports, the
internet, or VMS. Wirtz's 2005 study revealed that ``less-informed
drivers spend more time traveling than necessary, representing a
departure from the user-optimal traffic conditions simulated by VISTA.''
With the advancements in personal GPS information and its increased
accessibility, drivers are more likely to identify an optimal path
post-incident. It is critical to acknowledge that the assumptions
embedded in a model, along with its scope and scale, significantly
influence its functionality.

DTA models generally fall into two camps: microscopic and mesoscopic.
Microscopic models run on small scales and track the trajectories of
individuals. In contrast, mesoscopic models are more aggregated and
simplify variations in behavior; they involve elements of both static
modeling and dynamic microscopic models (Boyles, 2018). The level of
detail in microscopic models makes them highly realistic but impractical
for modeling large regions. A mesoscopic model that shows the paths of
individual vehicles but ignores traffic flow issues like turn conflicts
and lane changes would work well for modeling traffic flow over a
greater area (Boyles, 2018).

VISTA is an example of a mesoscopic model which showcases DTA's
capability for incident modeling. Microscopic models, like VISSIM, can
also be used for incident modeling. Microscopic models can track precise
locations of vehicles, driver behavior, and even vehicle
characteristics; this makes the models extraordinarily realistic but
impractical for modeling large regions (Boyles, 2018). In Australia, Dia
\& Cottman (2006) used VISSIM to evaluate incident management impacts on
two arterial routes (Coronation Drive and Milton Road) connecting the
western suburbs of Brisbane and the Central Business District. Another
framework used for incident modeling is the traffic simulator JDSMART.
This model was used by van Lint et al. (2012-01-01, 2012-01) for
incident simulation and to study how roadway policies influence
congestion.

MATSim, the Multi-Agent Transport Simulation Toolkit, has recently
gained recognition as a helpful software for incident modeling,
demonstrating a capacity for producing microscopic and mesoscopic
models. Operating as an open-source framework, MATSim is designed to
implement large-scale agent-based transport simulations. Using a
mesoscopic queue-based strategy, agents representing individuals seek
the shortest routes connecting their activities.

In his 2016 chapter of the MATSim manual, Dobler \& Nagel (2016)
emphasized the necessity and application of a within-day replanning tool
within the MATSim context. He elaborated that while MATSim's iterative
modeling approach fares well under ideal conditions and in achieving
user equilibrium, it falls short when dealing with unexpected
occurrences. This deficiency manifests as illogical behavior, such as
preemptive route changes before the incident's actual occurrence. For
example, Figure 1 illustrates a MATSim routing problem featuring
within-day replanning. It depicts an agent (a simulated individual)
navigating from the red dot to the green dot. A crash ensues along the
agent's assigned route at 14:02. Due to the iterative approach; however,
the agent switches to a different route at 14:00, two minutes before the
crash. This inconsistency exposes the limitations of an iterative
approach in modeling unanticipated behavior, underscoring the need for a
within-day replanning method, which utilizes a single iteration for
replanning rather than multiple.

\begin{figure}

{\centering \includegraphics{figures/within_day.png}

}

\caption{Within-day replanning approach for a MATSim routing problem.}

\end{figure}

While iterative systems leverage best-response modules, within-day
systems necessitate using a best-guess module. This approach means that
travel times can be optimized to a stable state with an iterative
approach, but this is not the case with a within-day approach. An
inherent attribute of within-day replanning is that it does not converge
to a user equilibrium, unlike an iterative process. Decisions, appearing
optimal in the moment, often reveal themselves as suboptimal upon
retrospective evaluation. Given the limited information available to the
agents in a within-day system, they may not necessarily choose the path
with the shortest travel time post-incident, as discussed by Dobler in
2016.

Replanning contains two categories: replanning an element of the
activity and executing the replanned elements. Elements include the
trip's start and end times, location, route, mode choice, or dropping of
a trip entirely. The system can execute plans for in-the-moment events
or those performed in the future. In a presently performed procedure, we
cannot conduct all replanning actions (e.g., we can no longer alter the
start time of an activity or the transport mode of a trip currently
being performed) (Dobler \& Nagel, 2016). Figure 2: Iterative and
within-day replanning MATSim loop illustrates where within-day
replanning fits within a MATSim loop.

\begin{figure}

{\centering \includegraphics{figures/matsim_loop.png}

}

\caption{Iterative and within-day replanning MATSim loop.}

\end{figure}

An alternative to iterative or within-day replanning only approaches is
to combine them. For example, we cannot thoroughly plan situations like
parking or car-sharing, requiring iterative and within-day replanning
methods. An agent can arrange a parking activity but cannot predict
which parking spots will be available when they arrive. Thus, we use
within-day replanning when the agent starts their parking choice.

In general, within-day or en-route replanning means that travelers
replan during the day or on their route, meaning that the simulation
needs to influence the agent while the network runs. Dobler \& Nagel
(2016) explains that we influence agents' decisions through loops or by
having users' routes dependent on the next link they choose. Because
going through all links and nodes at every step would be computationally
challenging, we may set certain links to be non-active and removed from
the computation (Dobler \& Nagel, 2016). The two implementation methods
Dobler described are plan-based implementation and replacing the agent.

In a plan-based implementation, a loop is used where each agent can
deliberate in every time step. The agent can decide that they have
nothing to deliberate and return immediately. Because the number of
links is typically much smaller than the number of agents in a scenario,
massive optimization is necessary to make the loop computationally
efficient. For this reason, we could ask each agent to choose a link
only when they need to decide.

Such event-driven planning requires the agents to be re-programmed to
have enough capabilities to be oriented about themselves (i.e., be able
to compute plausible routes). Agents will only need to perform such
computation when replanning is triggered by an event like an emergency
warning or unexpected congestion; otherwise, they will follow their
usual daily plans.

Re-programing agents and implementing within-day replanning, as shown in
Figure 2: Iterative and within-day replanning MATSim loop., requires the
implantation of a \emph{MobsimEngine}, which can be plugged into the
mobility simulator seen in the execution phase of Figure 2: Iterative
and within-day replanning MATSim loop (Axhausen et al., 2016-08-10,
2016-08). Dobler \& Nagel (2016) describes it this way, ``in every
simulated time step, the QSim iterates over all registered
\emph{MobsimEngines} and allows them to simulate the current time step.
Besides simulation of the traffic flows, those engines can also let
agents start or end activities'' (Dobler \& Nagel, 2016, p. 193). The
engines contain within-day replanning logic called
\emph{WithinDayEngine}, which helps track agents and adapt their plans
(Dobler \& Nagel, 2016). Not all agents need to compute plausible routes
at every turn, so an \emph{AgentSelector} selects the agents to be
replanned. \emph{AgentFilters} assist them in narrowing the search
population (Dobler \& Nagel, 2016). Lastly, \emph{TravelTimeCollectors}
are part of the \emph{WithinDayEngine} and provide actual link travel
times to the replanners by collecting and averaging travel times of
agents that have recently passed a link during a given time (Dobler \&
Nagel, 2016). The elements described above make up the plan-based
system.

A significant incident modeling, plan-based system study used MATSim to
simulate traffic incidents (Kaddoura \& Nagel, 2018). Their research
explains that MATSim models transport users as individual agents. MATSim
is iterative and allows users to adjust travel plans during a single
iteration, from iteration to iteration, or both (Kaddoura \& Nagel,
2018). Kaddoura and Nagel accessed their incident data via the HERE
application programming interface for traffic incidents. This incident
data included Traffic Message Channel (TMC) information indicating an
incident's cause and severity. With such robust data, Kaddoura and Nagel
could categorize incidents as long or short-term and model each
accordingly in MATSim. Long-term effects include multiple-day lane
closures, whereas short-term incidents affect transport supply for less
than a day. Their simulation was based on an inner-city network in
Berlin, Germany. Figure 3: Traffic incidents mapped on the Berlin
network illustrates the type of incidents modeled and their severity. In
this example, a crash on the southern inner-city motorway ring road led
to a full road closure, and several construction sites caused partial
capacity reductions.

\begin{figure}

{\centering \includegraphics{figures/berlin_capacity.png}

}

\caption{Traffic incidents mapped on the Berlin network.}

\end{figure}

Kaddoura \& Nagel (2018) found that long-term traffic incidents increase
traffic congestion and the average car travel time by 313 sec (+18\%)
per trip. Short-term traffic incidents increase the average travel time
per car trip by another 136 sec (+8\%). Additionally, they found that
for 44\% of all car trips, the agent's transport route contained at
least one road segment for which the capacity or speed limit was reduced
because of an incident. Their study concluded that networks in which
transport users had high levels of knowledge about the incidents and
resulting traffic congestion still experienced an increase in travel
time caused by long and short-term incidents. Finally, Kaddoura and
Nagel asserted that ``accounting for traffic incidents makes the model
more realistic, allowing for an improved policy investigation''
(Kaddoura \& Nagel, 2018, p. 885). The modeling performed by Kaddoura
and Nagel is just one example of research on MATSim's capacity for
incident-based simulations.

A MATSim model developed by Li \& Ferguson (2020) included various
rescheduling options, such as departure time, mode choice, and trip
cancellation. Their simulation found that if travelers received notice
of an incident, they would either depart early from their place of
origin or switch to public transport (Li \& Ferguson, 2020). The process
proposed by Li and Ferguson is beneficial because it allows agents to
reassess their mode choice or route assignment based on the notice of a
reported incident. Li and Ferguson show that users care about total
travel time and travel time variability (risk tolerance to a certain
degree). The receiving of notifications about incidents by agents
impacted both factors. They concluded that ``the provision of real-time
traffic information is a useful approach to mitigating the side-effects
of incidents through helping transport users efficiently adapt their day
plans'' (Li \& Ferguson, 2020, p. 96).

Additionally, they found that ``most of the travelers notified of being
affected by incidents are simulated to depart early or switch to public
transport, which effectively reduces the average travel time delay
caused by disruptions'' (Li \& Ferguson, 2020, p. 96). Their findings
validate the conclusions of Sisiopiku et al. (2007) that making incident
information available to agents leads to decreases in travel time and
congestion. Like the studies already mentioned, there have been various
modifications to and research on MATSim and its capacity.

In Thailand's capital, Bangkok, a study conducted by Peungnumsai et al.
(2019) demonstrated the potency of the MATSim framework in portraying
the impact of rush hour congestion on select traffic links. Peungnumsai
ran various simulation iterations, loading the selected links with a
different number of agents: 10, 100, and 500. The data collected and the
subsequent analysis substantiated MATSim's capability to demonstrate the
congestion-induced variations in travel time. Furthermore, it was
observed that as the number of agents in the simulation increased, there
was a proportional surge in computing time, physical memory usage, and
the size of the output file. Despite the scale of these simulations
being relatively small, MATSim has the capacity to simulate up to 10-100
million agents, encompassing various modes of transportation like
bicycles, motorbikes, cars, buses, and taxis (Peungnumsai et al., 2019).

In a contrasting study conducted in Copenhagen, Denmark, Paulsen et al.
(2018) utilized MATSim to contrast the reliability of automobile and
railway travel times. His methodology involved using an extension of
MATSim centered around an event-based public transport router, which
facilitates optimal route selection for public transport users by
comparing the effectiveness of routes over several iterations. Paulsen's
simulation of travel times for both cars and trains yielded an
interesting finding: passenger delays were significantly influenced by
the adaptiveness of their chosen routes. However, he noted that
passenger travel times tended to be more unpredictable than trains,
which escalated with the degree of route adaptiveness. He concluded that
the adaptiveness of route selection contributed to significant travel
time fluctuations, a conclusion that aligns with the findings of Li \&
Ferguson (2020).

In essence, the studies encapsulated in Section 2.2 validate the
effectiveness of the open-source software MATSim, in simulating traffic
incidents, congestion, and travel times. This evidence accentuates how
the proper application of MATSim or similar Dynamic Traffic Assignment
(DTA) models can account for traffic incidents, thereby enhancing the
realism of the models. This type of model, in turn, can facilitate more
effective policy investigation, as noted by Kaddoura \& Nagel (2018).

\hypertarget{summary}{%
\section{Summary}\label{summary}}

As explained in this section, there has been extensive research into
IMT's effectiveness and ability to restore traffic flow following long-
and short-term disturbances. Additionally, several studies have examined
how to effectively model traffic incidents and show their impact on
travel time, congestion, and mode choice. However, in these vast arrays
of findings, there is a gap in research on modeling IMT effectiveness
and incident impact on a loaded network with realistic agents. As a
result, it is difficult for researchers to understand how changes to
incident generation or IMT availability may impact traffic conditions.
In this research, we seek to combine these two strands, attempting to
model incident response in a mesoscopic simulation framework to bring
realism and detail to the IMT deployment question.

\bookmarksetup{startatroot}

\hypertarget{sec-methods}{%
\chapter{Methodology}\label{sec-methods}}

As highlighted in the \protect\hyperlink{sec-literature}{Literature
Review}, there is substantial evidence indicating that IMT can
effectively reduce RCT and ECU following traffic incidents.
Additionally, the effectiveness of DTA models in analyzing the impact of
such incidents has been well-documented. However, there is a lack of
comprehensive research evaluating IMT impact on entire traffic networks
and their associated agents. To address this gap, it is necessary that
we develop a model capable of simulating both traffic incidents and the
ensuing IMT interventions, with the objective of gauging the efficiency
of IMT deployments. Due to its proficiency in regional-scale incident
simulation and its authentic portrayal of driver behavior, MATSim has
been identified as the most suitable model for this research. This
section describes the methodology, expounding on the model's
capabilities, the requisite data inputs, and the benchmarks established
for determining IMT effectiveness.

Our methodology is structured around three main components: the
functionality of the MATSim model, the setup of IMT vehicles and
incidents, and the scenarios for comparative analysis. In the
\protect\hyperlink{sec-MATSim_mod}{Model Design in MATSim} we describe
the structure of the model and the functions it uses to represent
incidents and IMT response. In \protect\hyperlink{sec-model_imp}{Model
Implementaiton} we outline the data structure of the model by first
describing \protect\hyperlink{sec-IMT_setup}{IMT Setup}, then
\protect\hyperlink{sec-inc_data}{Incident Data and Sampling} and
conclude by describing the \protect\hyperlink{sec-scenarios}{Scenarios}
used for evaluating the impact of incidents and IMT.

\hypertarget{sec-MATSim_mod}{%
\section{Model Design in MATSim}\label{sec-MATSim_mod}}

MATSim is an open-source framework used for conducting extensive,
agent-based transportation simulations on a large scale. Operating as a
dynamic traffic simulation, it plays crucial roles in demand modeling
and agent-based mobility analysis (Dobler \& Nagel, 2016). Thanks to its
open-source architecture, MATSim enables the seamless integration of a
diverse array of modules and packages into its models. Users across the
platform can create, import, and modify these components, fostering a
collaborative and innovative environment.

For the purposes of our research, we developed the ImtModule, a
specialized MATSim extension designed to process incidents and IMT
responses within the simulation. This module leverages existing research
on incident simulation, Demand Rapid Transit (DRT), event handling, and
vehicle dispatch algorithms, building upon these foundations to enhance
the functionality of our model.

In this section, we describe some of the specific tools within MATSim
that we used and adapted to construct a comprehensive and functional
model. These tools include Scoring,Replanning, Network Change Events,
Vehicle Assignment, and Incident Response. Together, they contribute to
the realism and precision of our traffic simulations, particularly in
the context of responding to roadway incidents, ensuring that our model
provides accurate and reliable results.

\hypertarget{sec-MATSim_Score}{%
\subsection{Scoring and Replanning}\label{sec-MATSim_Score}}

In MATSim, each individual within the simulation is called an agent.
These agents follow daily schedules, partaking in various activities and
modes of travel. Their actions are evaluated using a point system, which
takes into account the specifics of their travel, as highlighted by
Nagel et al. (2016). Timely arrivals at destinations are rewarded with
positive points, whereas delays result in deductions. Furthermore,
different transportation modes are assigned utility scores, which play a
crucial role in shaping the agents' travel preferences and decisions.

Each agent possesses a memory that stores plans from a certain number of
iterations, as well as replanning strategies that dictate how agents can
adjust their plans from iteration to iteration Horni \& Nagel (2016).
The size of an agent's memory is typically dependent on the size of the
model being run. In the case of the large-scale Utah model, we opted to
limit the agents' plan memory to just five iterations. The replanning
strategies used include selecting the plan with the highest score 80\%
of the time, opting to reroute 10\% of the time, and adjusting activity
timings for the remaining 10\%.

Our selection of scoring and replanning parameters drew from the
research conducted by Kaddoura \& Nagel (2018). While their methodology
appeared sound at the outset, a more customized approach for our Utah
model would have been preferred. For example, the scoring factors for
transit and biking in the Berlin-based model by Kaddoura \& Nagel (2018)
were higher than what would typically apply in Utah. This likely
resulted in an inflated estimation of agents opting for these
transportation modes, diverging from actual observations in Utah.

Despite these challenges, the chosen parameters were ultimately
successful in steering agents towards a stable state of travel
equilibrium. Each simulation in the study ran for 450 iterations within
the MATSim framework. This process facilitated a convergence towards
equilibrium in travel behavior for the majority of scenarios.

\textless\textless{} I feel like this last paragraph is somewhat out of
place here, but I don't know if it belongs at the end of the section
either \textgreater\textgreater{}

\textless\textless{} I'm also just struggling with this section in
general. I think its good to talk about the strategies that were used,
but I feel like it's getting a little too in the weed, while at the same
time I'm not sure how to explain what is going on more simply. I also
wonder if that little bit about how our model likely over predicted the
usage of bikes and transits belongs in the limitations rather than here
in the methods. \textgreater\textgreater{}

\hypertarget{sec-NCE}{%
\subsection{Network Change Events}\label{sec-NCE}}

Within a MATSim network, each link is characterized by specific
attributes such as type, length, number of lanes, free-flow speed, and
capacity. To effectively simulate unexpected events and their subsequent
impacts on traffic flow, it is essential to dynamically adjust these
attributes. This capability, termed a Time-Dependent Network, is
explained in the MATSim textbook (Rieser, 2016) and is vital for
ensuring the realism and accuracy of our simulation.

Network Change Events (NCE) serve as the mechanism within MATSim for
modifying network attributes at precise moments during a simulation.
Detailed in Section 6.1 of the MATSim textbook (Rieser, 2016), the
implementation of NCE requires specific adjustments to the MATSim
configuration file to facilitate a time-variant network. These events
can modify a link's free-flow speed, number of lanes, or capacity. To
initiate a network change event, the system requires specific
information including the time of the event \texttt{startTime}, the
affected link(s) \texttt{link\ refID}, the type of change
\texttt{free-flow\ speed}, \texttt{lanes}, or \texttt{capacity}, and the
value of the change. NCE are the tools used in this study to demonstrate
the impact of both incidents and IMT arrivals.

\hypertarget{sec-imt_response}{%
\subsection{IMT Assignment and Response}\label{sec-imt_response}}

Within MATSim, the dispatch of one or more IMT is triggered by the
occurrence of an incident. The optimal IMT for the situation is
determined using a least-cost path dispatch algorithm, which bases its
calculations on vehicle paths while considering factors such as
congestion and link speed. The success of these methods heavily relies
on the IMT units' capability to navigate through traffic. In cases where
all IMT are occupied at the time of an incident, the algorithm waits
until a vehicle becomes available, and subsequently dispatches it to the
incident site.

Upon an IMT's arrival at an incident site, a NCE is activated via an
event handler, a MATSim tool that functions to log simulation events in
real-time. While incidents reduce a link's capacity, the IMT's arrival
triggers a NCE that restores 25\% of the capacity gap on the affected
link. The capacity gap is defined as the difference between the link's
full capacity and its reduced capacity during an incident. For incidents
requiring the response of multiple IMT, each arriving unit restores an
additional 25\% of the existing capacity gap.

Figure~\ref{fig-imt_capacity_restore} demonstrates the potential impact
of an incident lacking IMT intervention, compared with scenarios that
include the response of one or two IMT. This illustration highlights the
critical role of IMT, showcasing their ability to mitigate incident
impacts on network traffic flow.

\begin{figure}

{\centering \includegraphics{03_methods_files/figure-pdf/fig-imt_capacity_restore-1.pdf}

}

\caption{\label{fig-imt_capacity_restore}IMT capacity restoration upon
arrival example.}

\end{figure}

\hypertarget{sec-model_imp}{%
\section{Model Implementaiton}\label{sec-model_imp}}

To run the MATSim model with the ImtModule extension, a number of input
resources are necessary. For the model to function properly, the
following are needed:

\begin{itemize}
\tightlist
\item
  A plans file detailing the agents to be modeled, as well as their
  origins and destinations.
\item
  A network file with interconnected links, enabling travel for the
  agents specified in the plans file.
\item
  A configuration file outlining the scoring metrics of the simulation
  and establishing parameters pertaining to agent and IMT travel
  patterns.
\item
  An IMT file outlining the IMT starting locations and hours of
  operation.
\item
  An incidents file containing the necessary data to randomly effect NCE
  throughout the simulation.
\end{itemize}

The network and plans files used in this research were developed and
calibrated by Lant (2021) and Day (2022) as part of their research
projects studying accessibility and ride-hailing throughout the Wasatch
Front. The configuration file used in the model was adapted from the
Kaddoura \& Nagel (2018) file, which was used for their MATSim incident
analysis study. It was slightly modified to accommodate the IMT
development, but the parameters they set were largely left unaltered.
The IMT file was produced using data provided by UDOT and UHP, as
outline in \protect\hyperlink{sec-MATSim_mod}{IMT Setup}. The incident
data was compiled by Hyer (2023) in his research of IMT performance
measures and is explain in \protect\hyperlink{sec-inc_data}{Incident
Data and Sampling}.

\hypertarget{sec-IMT_setup}{%
\subsection{IMT Setup}\label{sec-IMT_setup}}

UDOT currently operates a fleet of 20 IMT, distributed across three
zones corresponding to Davis, Salt Lake, and Utah counties within the
Wasatch Front. Figure~\ref{fig-IMT_Map} provides a visual representation
of the county boundaries and the initial locations of both existing and
newly proposed IMT vehicles used in the simulation.

\begin{figure}

{\centering \includegraphics{figures/imt_gray_map.png}

}

\caption{\label{fig-IMT_Map}IMT starting locations example map.}

\end{figure}

In Figure~\ref{fig-IMT_Map}, circles indicate the locations of existing
IMT vehicles, while stars denote the proposed additions. These initial
positions are carefully selected to maintain a uniform distribution of
IMT vehicles across each county. Typically, IMT vehicles do not cross
county borders during operations since dispatch services are organized
at the county level. However, our MATSim network does not enforce such
restrictions, permitting vehicles to traverse county lines based on the
proximity of incidents. The specific starting points are noted in the
IMT file as starting links, streamlining their integration into MATSim.
While Figure~\ref{fig-IMT_Map} showcases the IMT distribution during the
evening shift, it is crucial to highlight that IMT allocation remains
constant throughout the morning and afternoon shifts. A 30-minute
overlap between shifts does not result in any operational issues, even
when two IMT vehicles are assigned to the same link. The initial setup
of IMT, although it does not replicate the real-world scenario of
drivers beginning their shifts from home, provides a viable solution for
our simulations. Considering the significant number of IMT operations
along major highways such as I-15, I-80, and I-215, and the daily
variations in starting locations, this strategic placement along key
routes is justified. In the 30-IMT scenario, all vehicles from the
20-IMT scenarios are retained and augmented with an additional 10 IMT,
ensuring comprehensive coverage across all three counties.

Our research primarily concentrates on evaluating the potential impacts
of expanding the IMT fleet, rather than examining the effects of their
starting positions. We hypothesize that increasing the number of IMT
vehicles, assuming they are evenly distributed, will enhance their
overall effectiveness.

\hypertarget{sec-inc_data}{%
\subsection{Incident Data and Sampling}\label{sec-inc_data}}

Hyer (2023) undertook concurrent IMT research and compiled a
comprehensive dataset of incidents requiring IMT intervention, drawing
on data from the UHP. He carefully ensured the completeness of each
incident record in the dataset, capturing crucial details such as the
incident start and end times, RCT, location, and extent of capacity
reduction.

Analyzing data from 2018 and 2022, Hyer (2023) successfully identified
411 unique incidents with varying degrees of severity, ranging from
property damage to fatal incidents. We utilized this carefully curated
dataset to selectively include specific incidents in the MATSim model.
It is crucial to acknowledge that these 411 incidents only constitute a
portion of all incidents reported by UHP during this time frame. A
significant number of additional incidents were not considered in the
analysis due to the absence of vital metrics necessary for a
comprehensive evaluation (e.g., start time, RCT, etc.). Nevertheless,
the integration of the 411 analyzed incidents with the additional
incomplete records provides insights, aiding in the quantification of
the total number of incidents within a specific time period. These
combined incident records were used in modeling daily incident
frequencies.

To generate ten distinct values representing daily incident frequencies,
we employed a randomized sampling technique. These values were
collectively termed Current Incident Frequencies as they were derived
from the original distribution of daily incidents. Furthermore, we
formulated a second set of ten daily incident values, named Increased
Incident Frequencies. These values were extracted from the upper portion
of the 2022 incident data and were specifically designed to assess the
resilience and efficacy of the IMT system under scenarios of markedly
increased daily incidents. The visual depiction of the original
distribution of daily incidents, alongside the distributions for both
the Current and Increased Incident Frequencies, is illustrated in
Figure~\ref{fig-incident_sampling_plot}.

\begin{figure}

{\centering \includegraphics{03_methods_files/figure-pdf/fig-incident_sampling_plot-1.pdf}

}

\caption{\label{fig-incident_sampling_plot}Incident sampling
distributions for current and increased incident frequencies.}

\end{figure}

In total, twenty values were selected, evenly split with ten allocated
to the Current Incident Frequency category, and the remaining ten to the
Increased Incident Frequency category. Each value was subsequently
paired with a unique three-digit seed number, utilized internally within
MATSim to ensure a randomized selection of incidents for each simulation
scenario. Following this, we employed the MATSim
\protect\hyperlink{sec-NCE}{Network Change Events} to integrate the
incidents into the simulation.

\hypertarget{sec-scenarios}{%
\subsection{Scenarios}\label{sec-scenarios}}

In the \protect\hyperlink{sec-inc_data}{Incident Data and Sampling}
section and Figure~\ref{fig-incident_sampling_plot}, we observe the
establishment and categorization of twenty distinct incident seeds into
either Current or Increased Incident frequencies. Each seed gave rise to
three separate simulation groups. The first group, No IMT, exclusively
features scenarios with incidents occurring without any intervention
from IMT. The second group includes incidents and the deployment of 20
IMT, while the third group features incidents managed with 30 IMT. To
facilitate efficient organization and comparative analysis, each
scenario was assigned a unique identifier, such as ``1-10-257.'' Within
this coding system, the first digit specifies the simulation group (No
IMT, 20 IMT, or 30 IMT), the second digit denotes the number of
incidents included in the simulation, and the third digit corresponds to
the seed value utilized for random incident selection.

In total, six scenario groups were established, as follows:

\begin{itemize}
\tightlist
\item
  No IMT, current incident frequency
\item
  No IMT, increased incident frequency
\item
  20 IMT, current incident frequency
\item
  20 IMT, increased incident frequency
\item
  30 IMT, current incident frequency
\item
  30 IMT, increased incident frequency
\end{itemize}

It is important to note, as described in the IMT Setup, that not all IMT
vehicles are operational simultaneously. Due to scheduling constraints,
the actual number of vehicles on the road at any given time is typically
half of the total fleet size.

The study utilizes the MATSim model for conducting simulations across
all three groups: No IMT, 20 IMT, and 30 IMT. Each simulation underwent
an internal comparison, as well as comparison against a Baseline
scenario devoid of incidents or IMT intervention. This comprehensive
analysis affords a holistic approach in assessing IMT effects on traffic
dynamics and their operational efficiency.

The primary metric for traffic impact analysis in this study is the
total vehicle hours of delay (VHD), dissected through three
investigative tiers: Network Links, Motorway Links, and Impacted Links.
Network Links offer a macroscopic view of the network-wide delay,
Motorway Links focused on major highways and freeways, and Impacted
Links provide a microscopic view of the delays at incident sites and
their immediate upstream links. This tiered approach ensures a thorough
analysis, capturing the overarching impact on traffic flow while also
honing in on critical areas affected by incidents.

In addition to VHD, the study investigates the performance and
operational efficiency of IMT. Metrics such as average travel times,
travel distances, and incident response times of IMT are compared across
the 20-IMT and 30-IMT groups. This, in turn, informs strategic decisions
regarding resource allocation and deployment, ensuring that IMT vehicles
are optimally utilized to mitigate traffic delays and enhance roadway
safety.

\bookmarksetup{startatroot}

\hypertarget{sec-results}{%
\chapter{Results}\label{sec-results}}

This section details the outcomes of the Utah IMT Optimization project,
employing the MATSim model to execute a series of simulations across a
range of scenario groups. Specifically, the groups---No IMT, 20 IMT, and
30 IMT---were compared with a Baseline scenario, facilitating an
evaluation of the repercussions of traffic incidents and the
effectiveness of IMT in alleviating traffic disruptions.

The following sections analyze the results derived from the simulated
scenarios. This analysis uses comparative metrics such as vehicle hours
of delay (VHD), the consequences of traffic incidents, and the dynamics
of the IMT responses in relation to the incidents they manage.

\hypertarget{vehicle-hours-of-delay}{%
\section{Vehicle Hours of Delay}\label{vehicle-hours-of-delay}}

The studies referenced in the \protect\hyperlink{sec-lit_imt_opt}{IMT
Optimization} section of the
\protect\hyperlink{sec-literature}{Literature Review} demonstrate the
efficacy of IMT in reducing RCT and ECU on roadway segments affected by
incidents. Similarly, the results from this transportation model
highlight the impact of IMT at reducing delay, particularly when
focusing on the segments of roadways where incidents occurred; see
\protect\hyperlink{sec-impacted}{Impacted Links}. In contrast to the
cited studies, our model also explored the broader implications of
incidents and their corresponding IMT responses on the simulated
network. In a majority of scenarios, these results also indicated a
positive correlation between IMT response and a decrease in VHD.

\hypertarget{network-hours-of-delay}{%
\subsection{Network Hours of Delay}\label{network-hours-of-delay}}

In the comparison of network VHD across simulations, the scenarios were
grouped by IMT response and incident frequency. Each group encompassed
ten simulated scenarios, which involved different selections of
incidents, with the exception of the Baseline scenario, which stands
alone. Table~\ref{tbl-network_delays_table} presents the average VHD for
each group, based on the delays recorded in the final iteration of each
simulation. These average VHD values are subsequently compared against
the Baseline scenario to calculate the percentage change in VHD.

\hypertarget{tbl-network_delays_table}{}
\begin{table}
\caption{\label{tbl-network_delays_table}Average Delay for Scenario Groups }\tabularnewline

\centering
\begin{tabular}[t]{llrr}
\toprule
\textbf{Group} & \textbf{Incident Frequency} & \textbf{Average VHD} & \textbf{Change (\%)}\\
\midrule
\cellcolor{gray!6}{Baseline} & \cellcolor{gray!6}{-} & \cellcolor{gray!6}{74568} & \cellcolor{gray!6}{0.0}\\
Incidents & Current & 103159 & 38.3\\
\cellcolor{gray!6}{Incidents} & \cellcolor{gray!6}{Increased} & \cellcolor{gray!6}{104178} & \cellcolor{gray!6}{39.7}\\
20 IMT & Current & 96697 & 29.7\\
\cellcolor{gray!6}{20 IMT} & \cellcolor{gray!6}{Increased} & \cellcolor{gray!6}{95678} & \cellcolor{gray!6}{28.3}\\
\addlinespace
30 IMT & Current & 93769 & 25.7\\
\cellcolor{gray!6}{30 IMT} & \cellcolor{gray!6}{Increased} & \cellcolor{gray!6}{93560} & \cellcolor{gray!6}{25.5}\\
\bottomrule
\end{tabular}
\end{table}

Upon comparing the results across different groups, it was observed that
scenarios with 30 IMT experienced the lowest average VHD. They were
closely followed by the 20 IMT scenarios, and, as expected, the
scenarios that involved incidents only registered the highest average
VHD values. It was also noted that introducing incidents to the baseline
scenario resulted in an average VHD increase of 39\%. However, this
increase decreased to an average of 29\% when 20 IMT were available, and
further reduced to 25.6\% with the availability of 30 IMT.

Further analysis of the data revealed that, compared to the No IMT
group, the 20 IMT group decreased the average VHD by 7.2\%, while the 30
IMT group reduced the average delay by 9.6\%. Lastly, when the 30 IMT
and 20 IMT groups were compared against each other, the former exhibited
an average of 2.6\% less VHD than the latter.

While the relationship between the IMT group and VHD appeared
straightforward, the correlation between Incident Frequency and VHD was
not as clear-cut. In the No IMT group, scenarios with increased incident
frequency showed only a one percent increase in VHD compared to those
with the current frequency. Intriguingly, for both the 20 IMT and 30 IMT
groups, an increase in incident frequency actually led to slight
decreases in average VHD. The cause of this decrease is unclear, but
potential explanations will be discussed in
\protect\hyperlink{sec-limitations}{Limiations}.

Given that the table reveals average delay values aggregated across
multiple scenarios within each group, a graphical representation can
enhance clarity regarding the inherent variance within these data
clusters. Figure~\ref{fig-network_violin_plot} illustrates this data
through violin plots.

\begin{figure}

{\centering \includegraphics{04_results_files/figure-pdf/fig-network_violin_plot-1.pdf}

}

\caption{\label{fig-network_violin_plot}Average network delay violins.}

\end{figure}

In Figure~\ref{fig-network_violin_plot}, each violin plot represents the
density distribution of delay values, with wider sections indicating
areas where numerous simulations converged around specific delay values.
Conversely, narrower sections suggest fewer simulations clustering
around those particular delay metrics. A dashed horizontal line is
superimposed to facilitate comparison of each group with the results
from the Baseline scenario. Additionally, diamond markers within each
plot denote the mean delay across all simulations in the respective
scenario group.

Upon examining these violin plots, several observations can be made. In
the No IMT group, the distribution of delay values has a relatively
narrow spread at the lower end, widening around the 100,000 mark, with
the mean delay slightly skewed toward 104,000. This skewness is
influenced by some values that approach 120,000 hours of delay. In
contrast, the 20 IMT group exhibits significant variability, as
reflected by its consistent width across the range of values. The
scenarios within the 30 IMT group show marginally reduced variability
compared to the 20 IMT group and feature distinct concentrations around
90,000 VHD and 100,000 VHD.

While the preceding section discussed delays across the entire network,
it is important to note that all simulated incidents were located on
motorway links, predominantly along the major interstates of Utah's
Wasatch Front. This encompasses key routes such as I-15, I-80, and
I-215, as well as other significant freeways and highways. The
subsequent section will provide a detailed analysis of the simulation
outcomes specifically related to these motorway links.

\hypertarget{motorway-link-hours-of-delay}{%
\subsection{Motorway Link Hours of
Delay}\label{motorway-link-hours-of-delay}}

The network used in our model is derived from an OpenStreetMap, which
Lant (2021) and Day (2022) also utilized for their research projects.
Within this network, the term `motorway' denotes a specific type of
link, also known as a freeway or expressway in different contexts. To
ensure consistency throughout this document, we primarily refer to these
road segments as `motorway' or `motorway links'. It is important to
note, however, that in the simulation, incidents can occur on both
interstates and major highways along the Wasatch Front.

To compare average simulation performances, the
Table~\ref{tbl-motorway_delays_table} table breaks down the average
Motorway VHD for each group, categorized by IMT response and incident
frequency.

\hypertarget{tbl-motorway_delays_table}{}
\begin{table}
\caption{\label{tbl-motorway_delays_table}Average VHD of Motorway Links }\tabularnewline

\centering
\begin{tabular}[t]{llrr}
\toprule
\textbf{Group} & \textbf{Incident Frequency} & \textbf{Average VHD} & \textbf{VHD Change (\%)}\\
\midrule
\cellcolor{gray!6}{Baseline} & \cellcolor{gray!6}{-} & \cellcolor{gray!6}{15335} & \cellcolor{gray!6}{0.0}\\
Incidents & Current & 24242 & 58.1\\
\cellcolor{gray!6}{Incidents} & \cellcolor{gray!6}{Increased} & \cellcolor{gray!6}{22321} & \cellcolor{gray!6}{45.6}\\
20 IMT & Current & 18924 & 23.4\\
\cellcolor{gray!6}{20 IMT} & \cellcolor{gray!6}{Increased} & \cellcolor{gray!6}{19176} & \cellcolor{gray!6}{25.0}\\
\addlinespace
30 IMT & Current & 17569 & 14.6\\
\cellcolor{gray!6}{30 IMT} & \cellcolor{gray!6}{Increased} & \cellcolor{gray!6}{18327} & \cellcolor{gray!6}{19.5}\\
\bottomrule
\end{tabular}
\end{table}

Table~\ref{tbl-motorway_delays_table} reveals that, in comparison to the
Baseline scenario, the average VHD on motorway links increased by
approximately 7,000-9,000 hours, or 45.6-58.1\%, when incidents were
introduced. The 20 IMT group, on average, exhibited a 24.2\% increase in
VHD from the Baseline, whereas the 30 IMT group experienced an average
VHD increase of 17\%.

At the motorway link level, the differences between the No IMT group and
the IMT groups becomes more pronounced they were for delays across the
entire network. Specifically, the 20 IMT group demonstrated an average
18.2\% decrease in VHD compared to the No IMT group, while the 30 IMT
group showed an average 22.9\% decrease in VHD.

Interestingly, the difficulty in correlating VHD with incident frequency
observed in Table~\ref{tbl-network_delays_table} manifests differently
in Table~\ref{tbl-motorway_delays_table}. The latter table indicates
that, within the IMT groups, an increase in incident frequency appears
to correspond with an increase in VHD. Specifically, the 20 IMT group
experiences an average VHD increase of 1.3\% when transitioning from
current to increased incident frequencies, while the 30 IMT group sees a
4.3\% uptick under the same conditions. In contrast, and quite
unexpectedly, the No IMT group shows a 7.9\% reduction in VHD when
comparing scenarios of current and increased incident frequencies. This
finding is particularly perplexing given that
Table~\ref{tbl-network_delays_table} suggests an overall increase in VHD
across the entire network for the No IMT group when incident frequency
increases.

A potential explanation for these unexpected VHD outcomes on motorway
links could be that, as part of their scoring and replanning process,
some MATSim agents may have opted for non-motorway links to reach their
destinations. This would essentially redistribute the delay from
motorway links to other parts of the network.

For a better understanding of the variances within the scenario groups,
Figure~\ref{fig-motorway_violin_plot} may provide additional insights.

\begin{figure}

{\centering \includegraphics{04_results_files/figure-pdf/fig-motorway_violin_plot-1.pdf}

}

\caption{\label{fig-motorway_violin_plot}Average motorway delay
violins.}

\end{figure}

In Figure~\ref{fig-motorway_violin_plot}, we observe distinct patterns
in the distribution of delays for different scenario groupings. Key
observations include:

\begin{itemize}
\tightlist
\item
  A wide span across the plots for both groupings of No IMT, indicating
  a significant variance in delays across those simulations.
\item
  A concentration of delays around the Baseline value of 15,000 VHD for
  both the 20 IMT and 30 IMT scenarios, as shown by the width of the
  plots at this point.
\item
  A narrowing of the IMT group plots as they transition to higher delay
  values, suggesting fewer instances of extreme delays.
\item
  The upper tails of the 20 IMT plots that extend beyond those of the 30
  IMT plots, suggesting that the 30 IMT fleet may be more effective at
  mitigating delays in outlier scenarios compared to the 20 IMT fleet.
\end{itemize}

The final section of our VHD analysis delves into the delays experienced
on incident links and their immediate upstream counterparts. This level
of analysis aligns with the methodologies employed in the studies by
Schultz et al. (2019) and Skabardonis et al. (1998), as it focuses on
the most direct repercussions of incidents and IMT. Unlike their focus
on the impacts of IMT on RCT and ECU, our investigation centers on VHD.
As detailed in \protect\hyperlink{sec-imt_response}{IMT Assignment and
Response}, the IMT in our simulation did not curtail the duration of
incidents (RCT); instead, they enhanced roadway capacity. Nonetheless,
given that ECU is intrinsically related to delay,
\protect\hyperlink{sec-impacted}{Impacted Links} offers an analogous
evaluation of IMT performance, similar to the analyses conducted by
Schultz et al. (2019) and Skabardonis et al. (1998).

\hypertarget{sec-impacted}{%
\subsection{Impacted Links}\label{sec-impacted}}

Impacted Links examined VHD on incident links and their immediate
upstream counterparts. Given the variation in link lengths across the
motorway, in some cases, analyzing just two additional links may not
fully capture the delays caused by a specific incident. Nevertheless,
Table~\ref{tbl-impacted_links} provides insights into how delays on
impacted links vary based on incidents and IMT deployment. For
additional context about the table: `Total VHD' represents the delay on
impacted links both during the incidents and for one hour after
clearance, aiming to capture any residual delay shock waves that an
incident might cause.

\hypertarget{tbl-impacted_links}{}
\begin{table}
\caption{\label{tbl-impacted_links}Impacted Links Table }\tabularnewline

\centering
\begin{tabular}[t]{llrr}
\toprule
\textbf{Group} & \textbf{Incident Frequency} & \textbf{Total VHD} & \textbf{Avg. Delay Per Inc. [hrs.]}\\
\midrule
\cellcolor{gray!6}{Baseline} & \cellcolor{gray!6}{Current} & \cellcolor{gray!6}{326} & \cellcolor{gray!6}{3.6}\\
Incidents & Current & 3808 & 42.3\\
\cellcolor{gray!6}{20 IMT} & \cellcolor{gray!6}{Current} & \cellcolor{gray!6}{723} & \cellcolor{gray!6}{8.0}\\
30 IMT & Current & 366 & 4.1\\
\cellcolor{gray!6}{Baseline} & \cellcolor{gray!6}{Increased} & \cellcolor{gray!6}{540} & \cellcolor{gray!6}{2.8}\\
\addlinespace
Incidents & Increased & 3154 & 16.3\\
\cellcolor{gray!6}{20 IMT} & \cellcolor{gray!6}{Increased} & \cellcolor{gray!6}{1645} & \cellcolor{gray!6}{8.5}\\
30 IMT & Increased & 1115 & 5.8\\
\bottomrule
\multicolumn{4}{l}{\textsuperscript{a} Note: Current contains 90 incidents, Increased contains 193}\\
\end{tabular}
\end{table}

Table~\ref{tbl-impacted_links} presents a division of the Baseline
scenario into two segments, for a more accurate comparison with the
other three scenarios. Despite the absence of incidents in the Baseline
scenario, its delay values are derived from the same links included in
the other scenarios.

The data in Table~\ref{tbl-impacted_links} indicates that, within the 30
IMT group, delay patterns align most closely with the baseline. This is
followed by the 20 IMT group, and subsequently, the No IMT group. It is
important to note that directly comparing the Total VHD of the Current
and Increased incident groups may not be appropriate due to variations
in sample sizes, as underscored by Table~\ref{tbl-impacted_links}. A
more apt comparison might be to evaluate the average delay experienced
per incident. Using this parameter, we observe an increase in the
average VHD for both the 20 and 30 IMT groups, correlating with an
uptick in the number of incidents. However, the scenarios involving No
IMT yield a different outcome: both Total VHD and the average delay per
incident exhibit a decrease when the incident frequency increased. A
more close examination of the data draws attention to a particular
scenario, Seed 141, which may have contributed an exceptionally large
delay to the incident links in the Current Incident category. This
anomaly could potentially explain the seemingly unexpected findings
observed in the No IMT Current Incident frequency scenarios.

For a more detailed analysis, the scatter plot in
Figure~\ref{fig-impacted_links_plot} categorizes the data based on seed
type. On the y-axis, the labels represent a combination of incident
numbers and seed values, with the format ``number\_seed'' (e.g.,
``12\_141'' denotes a scenario involving 12 incidents associated with
seed value 141).

\begin{figure}

{\centering \includegraphics{04_results_files/figure-pdf/fig-impacted_links_plot-1.pdf}

}

\caption{\label{fig-impacted_links_plot}Delay on impacted links sorted
by seed.}

\end{figure}

Figure~\ref{fig-impacted_links_plot} offers a detailed view of the VHD
on impacted links across the simulated scenarios. At a glance, the
Baseline and 30 IMT scenarios, represented by blue and orange dots
respectively, seem to predominantly cluster to the left of the pink
dots, which depict the No IMT scenarios. However, a more thorough
analysis reveals that in specific instances, the 20 IMT, 30 IMT, or even
both scenarios may underperform compared to the No IMT scenarios. This
seemingly unexpected observation suggests that there may be additional
factors, aside from link capacity, affecting the delay.

It is important to acknowledge the inherent dynamic nature of the MATSim
iterative process, where the ways in which agents re-plan their journeys
can sometimes have as significant, or potentially even greater, impact
on delays than changes in link capacity due to incidents or IMT.
Importantly, in scenarios with the highest delays, the introduction of
IMT seems to considerably reduce delay on the affected links.

Note that the x-axis has been limited to a maximum of 400+ VHD. This
limit enhances the visibility of the majority of data points. Without
this adjustment, the outlier point from the No IMT scenario with seed
141, which reported over 1,000 hours of delay, would have necessitated a
much wider scale, potentially obscuring the trends and patterns in the
rest of the data.

\hypertarget{imt-vehicle-analysis}{%
\section{IMT Vehicle Analysis}\label{imt-vehicle-analysis}}

Equally critical to understanding how IMT performance is assessing the
efficiency of each IMT in reaching their intended destinations. This
results segment delves into truck travel behavior, capturing metrics
such as average travel times and distances, along with their typical
incident response times. The analysis encompasses both 20 IMT and 30 IMT
scenarios.

\hypertarget{imt-travel-time}{%
\subsection{IMT Travel Time}\label{imt-travel-time}}

Travel times for IMT can be extracted from the event files, which are
produced as a standard MATSim output. These files provide insights into
the distance and time traveled by each IMT. Utilizing this truck travel
data, plots were generated to illustrate the average travel times and
distances for each dispatched IMT within a given scenario.
Figure~\ref{fig-truck_time_plot} illustrates the average travel time for
each dispatched IMT:

\begin{figure}

{\centering \includegraphics{04_results_files/figure-pdf/fig-truck_time_plot-1.pdf}

}

\caption{\label{fig-truck_time_plot}Average truck travel time sorted by
seed.}

\end{figure}

To compute the average travel time per truck we took the cumulative
travel time for all dispatched IMT in every scenario and then divided it
by the number of trucks deployed. Furthermore, an analysis of the IMT
travel data reveals that scenarios with 30 IMT generally dispatched more
trucks than scenarios with a fleet of only 20 IMT. A nearly analogous
methodology was employed to generate
Figure~\ref{fig-truck_distance_plot} discussed in the subsequent
section.

\hypertarget{imt-travel-distance}{%
\subsection{IMT Travel Distance}\label{imt-travel-distance}}

As with the variation in IMT travel time across different scenario,
there is a clear variance between 20 IMT and 30 IMT scenarios in terms
of the average distance traveled per dispatched IMT. These results are
visualized in Figure~\ref{fig-truck_distance_plot}.

\begin{figure}

{\centering \includegraphics{04_results_files/figure-pdf/fig-truck_distance_plot-1.pdf}

}

\caption{\label{fig-truck_distance_plot}Average truck distance traveled
sorted by seed.}

\end{figure}

The data presented in Figure~\ref{fig-truck_distance_plot} establishes a
direct correlation between an increased number of IMT and a decrease in
average distance traveled per team. Notably, the 30 IMT fleet benefited
in both time and distance scenarios by commencing from identical
locations as the 20 IMT fleet scenarios. This advantage was made more
noticeable by the addition of vehicles to bridge the spatial gaps
between the existing vehicles.

Altering the starting locations of the IMT or having them operate in a
roaming manner, as opposed to starting from a stationary location, can
significantly influence the time and distance traveled, presenting both
potential advantages and drawbacks. Although these factors, including
fleet size and vehicle starting locations, were highlighted by Lou et
al. (2011) as impactful in influencing IMT response times, it is
important to clarify that determining the optimal starting points for
IMT was not the primary focus of UDOT in this research. This aspect,
while not explored in the current study, presents a valuable opportunity
for future research, opening up an intriguing avenue for investigations
using the ImtModule MATSim extension associated with this report.

\hypertarget{imt-response-times}{%
\subsection{IMT Response Times}\label{imt-response-times}}

In the study conducted by Schultz et al. (2019), it is highlighted that,
in Utah, a one-minute increase in IMT response time (RT) results in an
approximate 0.8-minute increase in RCT. This finding emphasizes the
critical factor of IMT response times in reducing clearance times and
subsequent delays. In the simulation conducted, incidents requested the
support of one to four IMT units, with response times varying across
different scenarios.

\textless\textless{} Dr.~Macfarlane. You asked in your first edits if we
can validate Dr.~Schultz results. The answer is maybe. The issue is that
IMT only change capacity, so we couldn't confirm correlation between RT
and RCT. I could on the other hand, try and take the response time that
I present here and see if I can connect it to our delay values. At
present this data is just showing response time, and is not connected
back to delay or other performance measures -D.J.
\textgreater\textgreater{}

On average, across 280 simulated incidents, the arrival times in the 30
IMT scenarios were 4 minutes faster than those in the 20 IMT scenario,
as detailed in Table~\ref{tbl-truck_arrival_table}, which compares the
average arrival times of the 1st, 2nd, 3rd IMT.

\hypertarget{tbl-truck_arrival_table}{}
\begin{table}
\caption{\label{tbl-truck_arrival_table}Average Truck Arrival Times }\tabularnewline

\centering
\begin{tabular}[t]{lllllr}
\toprule
\textbf{Group} & \textbf{All IMT [mins]} & \textbf{1st [mins]} & \textbf{2nd [mins]} & \textbf{3rd [mins]} & \textbf{Total [hours]}\\
\midrule
\cellcolor{gray!6}{20 IMT} & \cellcolor{gray!6}{15.0} & \cellcolor{gray!6}{11.1} & \cellcolor{gray!6}{21.1} & \cellcolor{gray!6}{28.9} & \cellcolor{gray!6}{105}\\
30 IMT & 11.0 & 8.9 & 13.2 & 21.2 & 77\\
\cellcolor{gray65}{\cellcolor{gray!6}{Incidents}} & \cellcolor{gray65}{\cellcolor{gray!6}{280}} & \cellcolor{gray65}{\cellcolor{gray!6}{280}} & \cellcolor{gray65}{\cellcolor{gray!6}{116}} & \cellcolor{gray65}{\cellcolor{gray!6}{23}} & \cellcolor{gray65}{\cellcolor{gray!6}{280}}\\
\bottomrule
\end{tabular}
\end{table}

Table~\ref{tbl-truck_arrival_table} provides insights into the IMT
response patterns, capturing their arrival at 280 out of 283 incidents
across both scenarios. Note, the three unattended incidents fell outside
the IMT operational hours. In the incidents that were attended, support
from a second IMT was requested 116 times, a third IMT was requested 23
times, and a fourth IMT was called upon 3 times. However, due to the
extremely small number of incidents requiring a fourth IMT, this
category was considered too limited for significant analysis and was
subsequently excluded from both the Table~\ref{tbl-truck_arrival_table}
and the Figure~\ref{fig-truck_arrival_plot}. In comparing arrival times,
the scenarios with 30 IMT consistently outperformed those with 20 IMT,
demonstrating quicker response times across all incident categories. On
a cumulative level, the group with 20 IMT accrued a total of 105 hours
of travel time, while the 30 IMT scenarios reduced the total travel time
to 77 hours, marking a substantial decrease of nearly 27\%.

An in-depth examination of the IMT travel data reveals that in the 20
IMT scenarios, IMT were frequently dispatched to attend to several
incidents in quick succession, which adversely affected their arrival
times. On the other hand, the scenarios with 30 IMT, benefiting from a
larger fleet, were less prone to this pattern of deployment, ensuring
more timely arrivals.

Figure~\ref{fig-truck_arrival_plot} offers a comprehensive visual
representation, illustrating the variations in arrival times between the
20 and 30 IMT scenarios. Each data point on the plot signifies the
discrepancy in arrival times, with positive values denoting faster
responses by the 30 IMT fleet, and negative values indicating quicker
arrivals by the 20 IMT fleet. The overarching trend observed in the plot
underscores the improved performance of the 30 IMT fleet, especially
noticeable in scenarios characterized by a larger number of incidents.

\begin{figure}

{\centering \includegraphics{04_results_files/figure-pdf/fig-truck_arrival_plot-1.pdf}

}

\caption{\label{fig-truck_arrival_plot}Difference in IMT Arrival Times,
20 IMTs minus 30 IMTs.}

\end{figure}

The data presented in Figure~\ref{fig-truck_arrival_plot} clearly
demonstrates that the fleet of 30 IMT typically achieves faster arrival
times than the 20 IMT fleet. Although there are outliers present in each
group of trucks, it is especially apparent that in scenarios with an
increased frequency of incidents (18, 19, 20, and 21), the inclusion of
an additional 10 vehicles markedly optimizes the overall arrival times
of the trucks. This improvement is most apparent in the arrival times of
the 2nd and 3rd trucks.

In summary, the combined results from the VHD and IMT performance
analysis demonstrate the deficiency of IMT in mitigating delays,
particularly on the road segments directly impacted by incidents and
their immediate surroundings. Additionally, an increase in the size of
the vehicle fleet is directly associated with reductions in both the
average travel time per truck and the response times per incident,
underscoring the benefits of a larger IMT fleet in emergency response
situations.

\bookmarksetup{startatroot}

\hypertarget{sec-conclusions}{%
\chapter{Conclusions}\label{sec-conclusions}}

This section need not be overly long. You should address any limitations
of your results, such as dependence on underlying assumptions or
geographic scope. You should also provide a map for future research.

Finally, you should underline the contributions of this work and any
practical relevance.

\hypertarget{sec-limitations}{%
\section{Limitations}\label{sec-limitations}}

\hypertarget{within-day-replanning}{%
\subsection{Within-Day Replanning}\label{within-day-replanning}}

\textless\textless{} The model was meant to incorporates the concept of
within-day replanning to a certain extent, as elaborated in Chapter 30
of the MATSim textbook. I loaded the within-day replanning module but
didn't specify which agents needed to use it or the times that they
needed to use it. \textgreater\textgreater{}

\textless\textless{} Dr.~Macfarlane. Within-day replanning is not being
implemented in the way that I thought that it was. After re-reading the
literature review I realized that I had confused the replanning that
occurs from iteration to iteration with the replanning mentioned by
Kaddoura \& Nagel (2018) that only occurs for specific agents within the
simulation. \textgreater\textgreater{}

\textless\textless{} I do think it is still worth mentioning their
research, and I can discuss how we could have used within-day replanning
more effectively in the limitations section of this report. I am sorry
for the confusion and for not realizing the problem earlier. Perhaps
this section in the Methodology could discuss the strategy the model
uses from iteration to iteration. \textgreater\textgreater{}

\textless\textless{} I'll likely move this section to the limitations
and talk about it, but wanted to leave you a note here just in case you
were looking for this section - Daniel Jarvis\textgreater\textgreater{}

\bookmarksetup{startatroot}

\hypertarget{references}{%
\chapter*{References}\label{references}}
\addcontentsline{toc}{chapter}{References}

\markboth{References}{References}

\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\vadjust pre{\hypertarget{ref-axhausen2016}{}}%
Axhausen, K. W., Horni, A., \& Nagel, K. (2016-08-10, 2016-08).
\emph{The multi-agent transport simulation {MATSim}}. {Ubiquity Press}.

\leavevmode\vadjust pre{\hypertarget{ref-bennett2021}{}}%
Bennett, L. S. (2021). \emph{Analysis of benefits of an expansion to
UDOT's incident management program}.

\leavevmode\vadjust pre{\hypertarget{ref-bivina2016}{}}%
Bivina, G. R., Landge, V., \& Kumar, V. S. S. (2016-01-01, 2016-01).
Socio economic valuation of traffic delays. \emph{Transportation
Research Procedia}, \emph{17}, 513--520.
\url{https://doi.org/10.1016/j.trpro.2016.11.104}

\leavevmode\vadjust pre{\hypertarget{ref-boyles2018}{}}%
Boyles, S. (2018). \emph{Introduction to dynamic traffic assignment}.

\leavevmode\vadjust pre{\hypertarget{ref-day2022}{}}%
Day, C. S. (2022). \emph{Forecasting ride-hailing across multiple model
frameworks}.

\leavevmode\vadjust pre{\hypertarget{ref-dia2006}{}}%
Dia, H., \& Cottman, N. (2006). Evaluation of arterial incident
management impacts using traffic simulation. \emph{Intelligent Transport
Systems, IEE Proceedings}, \emph{153}, 242--252.
\url{https://doi.org/10.1049/ip-its:20055005}

\leavevmode\vadjust pre{\hypertarget{ref-dobler2016}{}}%
Dobler, C., \& Nagel, K. (2016). \emph{Within-day replanning}. {Ubiquity
Press}.

\leavevmode\vadjust pre{\hypertarget{ref-horni2016}{}}%
Horni, A., \& Nagel, K. (2016). \emph{More about conguring MATSim}.
{Ubiquity Press}.

\leavevmode\vadjust pre{\hypertarget{ref-hyer2023}{}}%
Hyer, J. (2023). \emph{Analysis of benefits of UDOT's expanded incident
management team program}.

\leavevmode\vadjust pre{\hypertarget{ref-kaddoura2018}{}}%
Kaddoura, I., \& Nagel, K. (2018). Using real-world traffic incident
data in transport modeling. \emph{Procedia Computer Science},
\emph{130}, 880--885. \url{https://doi.org/10.1016/j.procs.2018.04.084}

\leavevmode\vadjust pre{\hypertarget{ref-kim2012}{}}%
Kim, W., Franz, M., Chang, G.-L., \& University of Maryland (College
Park, Md. ). Dept. of C. and E. E. (2012). \emph{Enhancement of freeway
incident traffic management and resulting benefits.}

\leavevmode\vadjust pre{\hypertarget{ref-lant2021}{}}%
Lant, N. J. (2021). \emph{Estimation and simulation of daily activity
patterns for individuals using wheelchairs}.

\leavevmode\vadjust pre{\hypertarget{ref-li2020}{}}%
Li, J., \& Ferguson, N. (2020). A multi-dimensional rescheduling model
in disrupted transport network using rule-based decision making.
\emph{Procedia Computer Science}, \emph{170}, 90--97.
\url{https://doi.org/10.1016/j.procs.2020.03.012}

\leavevmode\vadjust pre{\hypertarget{ref-lou2011}{}}%
Lou, Y., Yin, Y., \& Lawphongpanich, S. (2011). Freeway service patrol
deployment planning for incident management and congestion mitigation.
\emph{Transportation Research Part C: Emerging Technologies},
\emph{19}(2), 283--295. \url{https://doi.org/10.1016/j.trc.2010.05.014}

\leavevmode\vadjust pre{\hypertarget{ref-nagel2016}{}}%
Nagel, K., Kickhofer, B., Horni, A., \& Charypar, D. (2016). \emph{A
closer look at scoring}. {Ubiquity Press}.

\leavevmode\vadjust pre{\hypertarget{ref-ozbay2013}{}}%
Ozbay, K., Iyigun, C., Baykal-Gursoy, M., \& Xiao, W. (2013).
Probabilistic programming models for traffic incident management
operations planning. \emph{Annals of Operations Research},
\emph{203}(1), 389--406. \url{https://doi.org/10.1007/s10479-012-1174-6}

\leavevmode\vadjust pre{\hypertarget{ref-pal2002}{}}%
Pal, R., \& Sinha, K. C. (2002). {SIMULATION MODEL FOR EVALUATING AND
IMPROVING EFFECTIVENESS OF FREEWAY SERVICE PATROL PROGRAMS}.
\emph{Journal of Transportation Engineering}, \emph{128}(4).

\leavevmode\vadjust pre{\hypertarget{ref-paulsen2018}{}}%
Paulsen, M., Rasmussen, T. K., \& Nielsen, O. A. (2018). \emph{Modelling
railway-induced passenger delays in multi-modal public transport
networks: {An} agent-based copenhagen case study using empirical train
delay data: 14th conference on advanced systems in public transport and
{TransitData} 2018}.

\leavevmode\vadjust pre{\hypertarget{ref-peungnumsai2019}{}}%
Peungnumsai, A., Miyazaki, H., Witayangkurn, A., \& Kii, M. (2019).
\emph{A review of {MATSim}: {A} pilot study of chatuchak, bangkok}.

\leavevmode\vadjust pre{\hypertarget{ref-rieser2016}{}}%
Rieser, H., Nagel. (2016). \emph{MATSim data containers}. {Ubiquity
Press}.

\leavevmode\vadjust pre{\hypertarget{ref-schultz2019}{}}%
Schultz, G. G., Saito, M., Eggett, D. L., Bennett, L. S., Hadfield, M.
G., Civil, B. Y. University. Dept. of, \& Environmental Engineering.
(2019). \emph{Analysis of performance measures of traffic incident
management in utah}.

\leavevmode\vadjust pre{\hypertarget{ref-sisiopiku2007}{}}%
Sisiopiku, V. P., Li, X., Mouskos, K. C., Kamga, C., Barrett, C., \&
Abro, A. M. (2007). Dynamic traffic assignment modeling for incident
management. \emph{Transportation Research Record}, \emph{1994}(1),
110--116. \url{https://doi.org/10.3141/1994-15}

\leavevmode\vadjust pre{\hypertarget{ref-skabardonis1998}{}}%
Skabardonis, A., Petty, K., Varaiya, P., \& Bertini, R. (1998).
Evaluation of the freeway service patrol ({FSP}) in los angeles.
\emph{PATH Research Report}.

\leavevmode\vadjust pre{\hypertarget{ref-vanlint2012}{}}%
van Lint, H., Miete, O., Taale, H., \& Hoogendoorn, S. (2012-01-01,
2012-01). Systematic framework for assessing traffic measures and
policies on reliability of traffic operations and travel time.
\emph{Transportation Research Record}, \emph{2302}(1), 92--101.
\url{https://doi.org/10.3141/2302-10}

\leavevmode\vadjust pre{\hypertarget{ref-wirtz2005}{}}%
Wirtz, J. J., Schofer, J. L., \& Schulz, D. F. (2005). Using simulation
to test traffic incident management strategies: {The} benefits of
preplanning. \emph{Transportation Research Record}, \emph{1923}(1),
82--90. \url{https://doi.org/10.1177/0361198105192300109}

\end{CSLReferences}

\cleardoublepage
\phantomsection
\addcontentsline{toc}{part}{Appendices}
\appendix

\hypertarget{event-handlers}{%
\chapter{Event Handlers}\label{event-handlers}}

This is the event handler

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{public} \KeywordTok{class}\NormalTok{ Bike }\OperatorTok{\{}
    \BuiltInTok{Integer}\NormalTok{ gears }\OperatorTok{=} \DecValTok{0}\OperatorTok{;}
    \BuiltInTok{String}\NormalTok{ color }\OperatorTok{=} \StringTok{"red"}\OperatorTok{;}
    \BuiltInTok{Double}\NormalTok{ price }\OperatorTok{=} \FloatTok{500.0}\OperatorTok{;}

    \FunctionTok{Bike} \OperatorTok{(}\BuiltInTok{Integer}\NormalTok{ gears}\OperatorTok{,} \BuiltInTok{String}\NormalTok{ color}\OperatorTok{,} \BuiltInTok{Double}\NormalTok{ price}\OperatorTok{)} \OperatorTok{\{}
        \KeywordTok{this}\OperatorTok{.}\FunctionTok{gears} \OperatorTok{=}\NormalTok{ gears}\OperatorTok{;}
        \KeywordTok{this}\OperatorTok{.}\FunctionTok{color} \OperatorTok{=}\NormalTok{ color}\OperatorTok{;}
        \KeywordTok{this}\OperatorTok{.}\FunctionTok{price} \OperatorTok{=}\NormalTok{ price}\OperatorTok{;}
    \OperatorTok{\}}
\OperatorTok{\}}
\end{Highlighting}
\end{Shaded}


\end{document}
